Add lazy option --start-at for meta-recipes (untested).

diff --git a/bin/Compile b/bin/Compile
--- a/bin/Compile
+++ b/bin/Compile
@@ -37,6 +37,7 @@ Add_Option_Boolean "S" "no-symlink" "Do not symlink."
 Add_Option_Boolean "T" "no-strip" "Do not strip executables."
 Add_Option_Boolean "G" "no-sign" "Do not sign program."
 Add_Option_Boolean "L" "lazy" "'Lazy mode': cut some corners when rebuilding; debugging aid: do NOT use it for building packages."
+Add_Option_Entry   "A" "start-at" "Skip sub-recipes when building a meta-recipe: start include list at given recipe; effective only with --lazy; debugging aid: do NOT use it for building packages."
 Add_Option_Boolean "D" "no-dependencies" "Do not try to fulfill dependencies."
 Add_Option_Boolean "a" "remove-archive" "Remove archive(s) after a successful build"
 Add_Option_Boolean "s" "remove-sources" "Remove sources after a successful build"
@@ -616,16 +617,30 @@ fi
 # Meta-recipe
 ##################################################
 
-foreach_if_array_set "include" '
-   iname=`echo $item | sed '\''s/--.*//'\''`
-   iversion=`echo $item | sed '\''s/.*--//'\''`
+if [ "${include[*]}" ]
+then
+   started=no
    export compileMetaRecipe=1
-   in_host $0 $compileoptions --keep --app-name "$appname" --version-number "$versionnumber" "$iname" "$iversion"
-   if [ "$?" -gt 0 ]
-   then
-      Die "Compilation of $iname $iversion failed."
-   fi
-'
+   for item in "${include[@]}"
+   do
+      iname=`echo "$item" | sed 's/--.*//'`
+      iversion=`echo "$item" | sed 's/.*--//'`
+      if Boolean "lazy" && Is_Entry_Set "start-at"
+      then
+         if [ "`Downcase $iname`" = "`Downcase $(Entry start-at)`" ]
+         then started=yes
+         fi
+         if [ "$started" = "no" ]
+         then continue
+         fi
+      fi
+      in_host $0 $compileoptions --keep --app-name "$appname" --version-number "$versionnumber" "$iname" "$iversion"
+      if [ "$?" -gt 0 ]
+      then
+         Die "Compilation of $iname $iversion failed."
+      fi
+   done
+fi
 
 if [ "$recipe_type" = "meta" ]
 then
