* Reverting commit 3279. Repo frozen. No new functionality. Will be commited after release. * Checking if we're in rootless before trying "chown"

diff --git a/bin/Compile b/bin/Compile
--- a/bin/Compile
+++ b/bin/Compile
@@ -9,7 +9,6 @@
 . ScriptFunctions
 Import OptionParser
 Import File
-Import String
 Import Terminal
 Import GoboLinux
 Import Array
@@ -456,7 +455,7 @@ function export_marked() {
 ##################################################
 
 Check_Dir_Variable compileDir
-$sudo_exec chown `whoami` "${compileDir}"
+[ -z "$ROOTLESS_GOBOLINUX" ] && $sudo_exec chown `whoami` "${compileDir}"
 [ "${compileRecipeDirs[*]}" ] || Die "Array \$compileRecipeDirs is not set. Please update your Compile.conf."
 for compileRecipeDir in "${compileRecipeDirs[@]}"
 do
@@ -466,7 +465,7 @@ Check_Dir_Variable compileDependenciesDir
 Check_Dir_Variable compileArchivesDir
 Check_Dir_Variable compileSourcesDir
 Check_Dir_Variable compilePackedRecipesDir
-$sudo_exec chown `whoami` "${compileSourcesDir}"
+[ -z "$ROOTLESS_GOBOLINUX" ] && $sudo_exec chown `whoami` "${compileSourcesDir}"
 
 ##################################################
 # Find and Get Recipe
@@ -641,15 +640,25 @@ then versionnumber=`Entry "version-number"`
 else versionnumber="$version"
 fi
 
-upperversion=`Uppercase "$versionnumber"`
-for upperscm in CVS SVN GIT BZR HG
-do
-   if [ "$upperversion" = "$upperscm" ]
-   then
-      versionnumber=`date +%Y%m%d`"-$upperversion"
-      break
-   fi
-done
+if [ "$versionnumber" = "CVS" -o "$versionnumber" = "cvs" ]
+then versionnumber=`date +%Y%m%d`"-CVS"
+fi
+
+if [ "$versionnumber" = "SVN" -o "$versionnumber" = "svn" ]
+then versionnumber=`date +%Y%m%d`"-SVN"
+fi
+
+if [ "$versionnumber" = "GIT" -o "$versionnumber" = "git" ]
+then versionnumber=`date +%Y%m%d`"-GIT"
+fi
+
+if [ "$versionnumber" = "BZR" -o "$versionnumber" = "bzr" ]
+then versionnumber=`date +%Y%m%d`"-BZR"
+fi
+
+if [ "$versionnumber" = "HG" -o "$versionnumber" = "hg" ]
+then versionnumber=`date +%Y%m%d`"-HG"
+fi
 
 target=`Get_Dir runtime $appname $versionnumber`
 settings_target=`Get_Dir runtimeSettings $appname $versionnumber`
@@ -809,7 +818,11 @@ fi
 # Construct some variable arrays
 ##################################################
 
-for var in url mirror_url file file_size file_md5 cvs cvs_module svn git bzr hg
+if ! [ -n "${cvs}${svn}${git}${bzr}${hg}${url}${urls[*]}" ]
+then Die "Missing URL, CVS, SVN, GIT, BZR or HG in recipe '$recipe'."
+fi
+
+for var in url file file_size file_md5
 do
    eval '
       if [ -n "$'$var'" -a ! -n "${'$var's[*]}" ]
@@ -818,19 +831,11 @@ do
    '
 done
 
-function is_scm_recipe() {
-   [ "${cvss[*]}${svns[*]}${gits[*]}${bzrs[*]}${hgs[*]}" ]
-}
-
-if [ ! "${urls[*]}" ] && ! is_scm_recipe
-then Die "Missing URL or repository information in recipe '$recipe'."
-fi
-
 if ! [ "${files[*]}" ]
 then files=(`Map basename "${urls[@]}"`)
 fi
 
-if is_scm_recipe
+if [ "${cvs}" -o "${svn}" -o "${git}" -o "${bzr}" -o "${hg}" ]
 then
    if [ -z "${dir}" ]
    then
@@ -887,11 +892,31 @@ fi
 # Get & Unpack sources
 ##################################################
 savedir="--save-to $(echo ${dir}|sed s/"\(.*\)\/${save_directory}.*"/"\1"/) --save-directory ${save_directory}"
-if is_scm_recipe
+if [ "$cvs" ]
 then
    # If sources were already fetched, do not patch again
    [ -d "${dir}" ] && skippatching=yes
-   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching snapshot from repository."
+   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching CVS snapshot."
+   Boolean "no-build" && exit 0
+elif [ "$svn" ]
+then
+   [ "${dir}" -a -d "${dir}" ] && skippatching=yes
+   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching SVN snapshot."
+   Boolean "no-build" && exit 0
+elif [ "$git" ]
+then
+   [ "${dir}" -a -d "${dir}" ] && skippatching=yes
+   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching GIT snapshot."
+   Boolean "no-build" && exit 0
+elif [ "$bzr" ]
+then
+   [ "${dir}" -a -d "${dir}" ] && skippatching=yes
+   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching BZR snapshot."
+   Boolean "no-build" && exit 0
+elif [ "$hg" ]
+then
+   [ "${dir}" -a -d "${dir}" ] && skippatching=yes
+   Boolean "no-web" || in_host FetchArchive $verbose $batch $savedir "$recipe" "$archrecipe" || Die "Error fetching HG snapshot."
    Boolean "no-build" && exit 0
 else
    if ! Boolean "no-web"
@@ -935,7 +960,7 @@ else
       fi
       case $REPLY in
       [Rr]) rm -rf "${basedirs[0]}" 2>/dev/null || $sudo_exec rm -rf "${basedirs[0]}" ;;
-      [Bb]) mv "${basedirs[0]}" "${basedirs[0]}.backup" || { $sudo_exec mv "${basedirs[0]}" "${basedirs[0]}.backup"; $sudo_exec chown -R `whoami` "${basedirs[0]}.backup"; } ;;
+      [Bb]) mv "${basedirs[0]}" "${basedirs[0]}.backup" || { $sudo_exec mv "${basedirs[0]}" "${basedirs[0]}.backup"; [ -z "$ROOTLESS_GOBOLINUX" ] && $sudo_exec chown -R `whoami` "${basedirs[0]}.backup"; } ;;
       [Uu]) unpack=no ;;
       [Cc]) exit 0 ;;
       esac # esac is ridiculous.
@@ -987,7 +1012,7 @@ else
 
       if [ "$unpack_files" -o $i -eq $(( ${#files[@]} - 1 )) ]; then
          mkdir -p "$drop"
-         $sudo_exec $chown -R --reference="${tempdir}" "${tempdir}"
+         [ -z "$ROOTLESS_GOBOLINUX" ] && $sudo_exec $chown -R --reference="${tempdir}" "${tempdir}"
          Quiet mv "${tempdir}"/"$skipdir"/* "${tempdir}"/"$skipdir"/.[A-z]* "$drop"
          rm -rf "${tempdir}"
          Quiet popd
