r393@Hermes:  jonas | 2008-07-05 18:24:26 +0200  Catch errors from wget

diff --git a/bin/GetRecipe b/bin/GetRecipe
--- a/bin/GetRecipe
+++ b/bin/GetRecipe
@@ -127,6 +127,8 @@ do
       else wget="wget"
       fi
       $wget -t 5 "$rawrecipe" -O - -q | Verbose tar xjvf - -C "$compileGetRecipeDir"
+      [ ${PIPESTATUS[0]} != 0 ] && Die "Could not fetch recipe. Check URL (${rawrecipe})"
+      
       if [ -d "$compileGetRecipeDir/$app/$version" ]
       then
          echo "$compileGetRecipeDir/$app/$version"
