MakeRecipe uses FetchArchive. Closes bug #116. (Which wasn't really a bug!!!)

diff --git a/bin/MakeRecipe b/bin/MakeRecipe
--- a/bin/MakeRecipe
+++ b/bin/MakeRecipe
@@ -158,58 +158,40 @@ if [ "$cvs" = "yes" ]
 then
    echo "cvs=$cvs_server" >> "$recipefile"
    echo "cvs_module=$cvs_module" >> "$recipefile"
-
-   Quiet pushd "$compileSourcesDir"
-   cvs -d "$cvs_server" checkout "$cvs_module"
-   file_contents=`Temporary_File`
-   find "$cvs_module" >> "$file_contents"
-   Quiet popd
+   checkoutdir="$compileArchivesDir/$packagename-cvs"
 elif [ "$svn" = "yes" ]
 then
    echo "svn=\"$svn_uri\"" >> "$recipefile"
-
-   Quiet pushd "$compileSourcesDir"
-   svn checkout $svn_uri "${packagename}-svn"
-   file_contents=`Temporary_File`
-   find "${packagename}-svn" >> "$file_contents"
-   Quiet popd
+   checkoutdir="$compileArchivesDir/$packagename-svn"
 else
    echo "url=\"$url\"" >> "$recipefile"
-
-   Quiet pushd "$compileArchivesDir"
-   basefile="$(basename "$source_url")"
-   file="$PWD/$basefile"
-   if ! Boolean "no-fetch"
+   file="$compileArchivesDir/$(basename "$source_url")"
+   if { ! Boolean "no-fetch" ;} && Starts_With "http" "$source_url"
    then
-      if Starts_With "http" "$source_url"
+      # Detect URLs that feature redirects, like funky "...download.php?pkg=1234" URLs.
+      file_headers=`Temporary_File`
+      $wget --spider --server-response "$source_url" 2> $file_headers
+      filename=`grep -i "content-disposition:.*filename=" "$file_headers" | sed 's/.*filename=\([^;]*\).*/\1/;s/^["'\'']//;s/["'\'']$//'`
+      if [ -n "$filename" -a "$filename" != "$basefile" ]
       then
-         file_headers=`Temporary_File`
-         $wget --spider --server-response "$source_url" 2> $file_headers
-         filename=`grep -i "content-disposition:.*filename=" "$file_headers" | sed 's/.*filename=\([^;]*\).*/\1/;s/^["'\'']//;s/["'\'']$//'`
-         if [ -n "$filename" -a "$filename" != "$basefile" ]
-         then
-            basefile="$filename"
-            file="$PWD/$basefile"
-            echo "file=\"$basefile\"" >> "$recipefile"
-         fi
-         rm $file_headers
+         basefile="$filename"
+         file="$compileArchivesDir/$basefile"
+         echo "file=\"$basefile\"" >> "$recipefile"
       fi
-
-      $wget -O "$basefile" --passive-ftp -c "$source_url" || \
-      $wget -O "$basefile" --passive-ftp "$source_url" || \
-      $wget -O "$basefile" "$source_url" || {
-         Log_Error "Couldn't fetch file, URL may be invalid."
-         exit 1
-      }
-   else
-      if ! [ -e "$file" ]
-      then
-         Log_Error "--no-fetch used, but file is not available."
-         exit 1
-      fi
+      rm $file_headers
    fi
-   Quiet popd
-   
+fi
+
+if ! Boolean "no-fetch"
+then
+   FetchArchive "$recipefile" || Die "Could not fetch sources."
+elif ! [ -e "$file" ]
+then
+   Die "--no-fetch used, but file is not available."
+fi
+
+if [ "$url" ]
+then
    echo "file_size="`Get_Size "$file"` >> "$recipefile"
    echo "file_md5="`Get_MD5 "$file"` >> "$recipefile"
    
@@ -223,6 +205,12 @@ else
    then
       echo "dir='$bdir'" >> "$recipefile"
    fi
+elif [ "$cvs" = "yes" -o "$svn" = "yes" ]
+then
+   Quiet pushd "$compileSourcesDir"
+   file_contents=`Temporary_File`
+   find "$checkoutdir" >> "$file_contents"
+   Quiet popd
 fi
 
 if grep -q "configure.in$" "$file_contents" \
