Spin recipe update code out into a function (in preparation for updating inside architectures and #227)

diff --git a/bin/NewVersion b/bin/NewVersion
--- a/bin/NewVersion
+++ b/bin/NewVersion
@@ -139,52 +139,55 @@ done
 sed -i 's/is_\(.*\)=yes/recipe_type=\1/
 s/compileprogram/configure/' Recipe
 
-source Recipe
-unset newarchrecipedir
-arch=`Get_Architecture`
-if [ -e "$newrecipedir/$arch/Recipe" ] 
-then
-   newarchrecipedir="$newrecipedir/$arch/Recipe"
-   source "$newarchrecipedir"
-fi
-
-if [ "$newurl" ]
-then
-   url="$newurl"
-fi
-
-if Starts_With "http:" $url
-then
-   Quiet pushd "$compileArchivesDir"
-   Log_Normal "Checking URL '$url'..."
-   quietflag="--quiet"
-   Boolean "verbose" && unset quietflag
-   if ! wget -t 5 $quietflag --spider "$url"
+Update_Recipe() {
+   source Recipe
+   unset newarchrecipedir
+   arch=`Get_Architecture`
+   if [ -e "$newrecipedir/$arch/Recipe" ] 
    then
-      Log_Terse "URL may be invalid. Please check."
+      newarchrecipedir="$newrecipedir/$arch/Recipe"
+      source "$newarchrecipedir"
    fi
-   Quiet popd
-fi
 
-
-if ls *.patch &> /dev/null
-then
-   Log_Terse "This recipe contains patches. Please check if they still apply."
-fi
-
-if [ "$url" ]
-then
-   Log_Normal "Downloading source code..."
-   if ! FetchArchive "$newrecipedir/Recipe" $newarchrecipedir
+   if [ "$newurl" ]
    then
-      rm -rf "$newrecipedir"
-      Die "Could not download source code, aborting."
+      url="$newurl"
    fi
-   [ -z "${file}" ] && file="`basename $url`"
-   filesize="`Get_Size $compileArchivesDir/$file`"
-   filemd5="`Get_MD5 $compileArchivesDir/$file`"
+
+   if Starts_With "http:" $url
+   then
+      Quiet pushd "$compileArchivesDir"
+      Log_Normal "Checking URL '$url'..."
+      quietflag="--quiet"
+      Boolean "verbose" && unset quietflag
+      if ! wget -t 5 $quietflag --spider "$url"
+      then
+         Log_Terse "URL may be invalid. Please check."
+      fi
+      Quiet popd
+   fi
+
+   if ls *.patch &> /dev/null
+   then
+      Log_Terse "This recipe contains patches. Please check if they still apply."
+   fi
+
+   if [ "$url" ]
+   then
+      Log_Normal "Downloading source code..."
+      if ! FetchArchive "$newrecipedir/Recipe" $newarchrecipedir
+      then
+         rm -rf "$newrecipedir"
+         Die "Could not download source code, aborting."
+      fi
+      [ -z "${file}" ] && file="`basename $url`"
+      filesize="`Get_Size $compileArchivesDir/$file`"
+      filemd5="`Get_MD5 $compileArchivesDir/$file`"
    sed -i "s,\(^url=.*\),\1\nfile_size=$filesize\nfile_md5=$filemd5,g" "$newrecipedir/Recipe"
-fi
+   fi
+}
+
+Update_Recipe
 
 Log_Normal "Recipe template for $packagename $newversion created"
 Log_Normal "Printing result ($newrecipedir/Recipe):"
