Disabling xorg.conf creation and adjustment.

diff --git a/tools/LiveCD/bin/ConfigureLiveCD b/tools/LiveCD/bin/ConfigureLiveCD
--- a/tools/LiveCD/bin/ConfigureLiveCD
+++ b/tools/LiveCD/bin/ConfigureLiveCD
@@ -6,13 +6,13 @@ source StartFunctions
 ######################################
 # X11
 ######################################
-if [ -d ${goboPrograms}/Xorg ]
-then
-	msg_no_nl "Starting X11 detection (<esc> to skip)" 
-	skip_on_esc 3000 && echo && { 
-	   GenXorgConf > /tmp/xorg.conf && mv /tmp/xorg.conf ${goboPrograms}/Xorg/Settings/X11/xorg.conf || echo FAILED
-	} || echo '<SKIPPED>'
-fi
+#if [ -d ${goboPrograms}/Xorg ]
+#then
+#	msg_no_nl "Starting X11 detection (<esc> to skip)" 
+#	skip_on_esc 3000 && echo && { 
+#	   GenXorgConf > /tmp/xorg.conf && mv /tmp/xorg.conf ${goboPrograms}/Xorg/Settings/X11/xorg.conf || echo FAILED
+#	} || echo '<SKIPPED>'
+#fi
 
 ######################################
 # Choose language
@@ -75,9 +75,9 @@ loadkeys $MAPNAME
 ######################################
 # Adjusting xorg.conf
 ######################################
-if [ -d ${goboPrograms}/Xorg -a -f ${goboPrograms}/Xorg/Settings/X11/xorg.conf ]
-then
-	msg "Adjusting xorg.conf"
-	cat ${goboPrograms}/Xorg/Settings/X11/xorg.conf | ModifyXorgConf `cat ${goboTemp}/setup/keymap` > /tmp/xorg.conf.$$ 
-	cp -f /tmp/xorg.conf.$$ ${goboPrograms}/Xorg/Settings/X11/xorg.conf
-fi
+#if [ -d ${goboPrograms}/Xorg -a -f ${goboPrograms}/Xorg/Settings/X11/xorg.conf ]
+#then
+#	msg "Adjusting xorg.conf"
+#	cat ${goboPrograms}/Xorg/Settings/X11/xorg.conf | ModifyXorgConf `cat ${goboTemp}/setup/keymap` > /tmp/xorg.conf.$$ 
+#	cp -f /tmp/xorg.conf.$$ ${goboPrograms}/Xorg/Settings/X11/xorg.conf
+#fi
