new style of recipe management: /Data/Compile/Recipes is a git repo

diff --git a/Functions/Compile b/Functions/Compile
--- a/Functions/Compile
+++ b/Functions/Compile
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 Import File
+Import RecipeTools
 
 ##################################################
 # Setting up variables
@@ -126,59 +127,54 @@ function Version_Number_From_Url() {
 }
 
 Find_Recipe() {
-   nameorrecipe="$1"
+   app="$1"
    versionandrevision="$2"
    tarballurl="$3"
-
+   
    if Has_Substring "$versionandrevision" ":/"
    then
       tarballurl="$2"
       versionandrevision=$(Version_Number_From_Url "$tarballurl")
    fi
-
-   # support for direct recipe passing
-   if [ -f "${nameorrecipe}/Recipe" -o "`echo ${nameorrecipe} | grep "/"`" ] || Ends_With "--recipe.tar.bz2" "${nameorrecipe}"
+   
+   Find_Recipe_Program_And_Version pull "$app" "$versionandrevision"
+   err=$?
+   if [ "$err" = 0 ]
    then
-      rawrecipes="${nameorrecipe}"
-      Log_Normal "Using passed recipe $rawrecipes"
-   else
-      app="${nameorrecipe}"
-      version="$(String_Version "$versionandrevision")"
-
-      # Find recipe:
-      Log_Normal "Locating a recipe for $app $versionandrevision..."
-      String_To_Array rawrecipes "$(FindPackage $noweb --full-list --type=recipe "$app" "$versionandrevision" 2> /dev/null)"
-      [ "${rawrecipes[*]}" ] || {
-         FindPackage $noweb --type=recipe "$app" &> /dev/null && {
-            Log_Terse "Could not find recipe for $app $versionandrevision."
-            { Boolean "batch" || Ask_Continue "Attempt to create recipe for version $version?"
-            } && NewVersion $app $version "${tarballurl}"  && {
-               String_To_Array rawrecipes "$(FindPackage $noweb --full-list --type=recipe "$app" "$version" 2> /dev/null)"
-            }
-         }
-      } || {
-         Log_Error "Could not find recipe for $app $versionandrevision"
-         GetAvailable -t recipe|cut -d' ' -f2|uniq|Corrections --log-name Compile --stdin "$app">&2
-         if Is_Empty "$(Arg 3)"
-         then Die_With $errorNotFound "Could not find recipe for $app $versionandrevision"
-         else
-            Log_Normal "Will attempt to create one based on URL '$(Arg 3)'..."
-            if MakeRecipe --batch "$(Arg 1)" "$(Arg 2)" "$(Arg 3)"
-            then
-               Log_Normal "Will attempt to use newly created recipe..."
-               String_To_Array rawrecipes "$(FindPackage $noweb --full-list --type=recipe "$app" "$version" 2> /dev/null)"
-            else Die_With $errorNotFound "Could not create recipe for $app $versionandrevision"
-            fi
-         fi
-      }
-      Log_Normal "Found recipe for $app $versionandrevision"
+      echo "$recipedir/Recipe"
+      return 0
    fi
 
-   bakedrecipedir=$(in_host GetRecipe "${rawrecipes[@]}")
-   [ "$bakedrecipedir" ] || Die "Error getting recipe"
-   Log_Normal "Recipe placed in $bakedrecipedir"
-   [ -f "$bakedrecipedir/Recipe" ] || Die "$bakedrecipedir/Recipe not found"
-   echo "$bakedrecipedir/Recipe"
+   Find_Recipe_Program_And_Version no "$app" ""
+   err=$?
+   if [ "$err" = 0 ] && [ "$versionandrevision" ]
+   then
+      Log_Terse "Could not find recipe for $app $versionandrevision."
+      { Boolean "batch" || Ask_Continue "Attempt to create recipe for version $version?"
+      } && NewVersion $app $version "${tarballurl}"
+      Find_Recipe_Program_And_Version no "$app" "" && {
+         echo "$recipedir/Recipe"
+         return 0
+      }
+      return 1
+   fi
+
+   Log_Error "Could not find a recipe for $app"
+   ls $compileRecipesDir | cut -d' ' -f2 | uniq | Corrections --log-name Compile --stdin "$app">&2
+   if [ "$tarballurl" ]
+   then
+      Log_Normal "Will attempt to create one based on URL '$tarballurl'..."
+      if MakeRecipe --batch "$app" "$versionandrevision" "$tarballurl"
+      then
+         Log_Normal "Will attempt to use newly created recipe..."
+         Find_Recipe_Program_And_Version no "$app" "$versionandrevision" && {
+            echo "$recipedir/Recipe"
+            return 0
+         }
+      fi
+   fi
+
+   return 1
 }
 
 Available_BuildTypes() {
diff --git a/bin/ContributeRecipe b/bin/ContributeRecipe
--- a/bin/ContributeRecipe
+++ b/bin/ContributeRecipe
@@ -1,6 +1,6 @@
 #!/bin/bash
-# ContributeRecipe - submits a GoboLinux recipe to the review panel
-# Copyright (C) 2008 Michael Homer
+# ContributeRecipe - submits a GoboLinux recipe for review
+# Copyright (C) 2008-2020 Michael Homer
 # 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,6 +22,7 @@ Import GoboLinux
 Import OptionParser
 Import Versions
 Import Archive
+Import RecipeTools
 
 Parse_Conf Compile/Compile.conf
 
@@ -34,49 +35,161 @@ helpOnNoArguments=yes
 scriptUsage="{ <recipe dir> | <recipe name> [<recipe version>] }"
 scriptExample="firefox"
 Add_Option_Boolean "p" "pretend" "Don't really submit, just dump the report to stdout."
+Add_Option_Boolean "g" "gobo" "GoboLinux developer: push straight to repo."
 Parse_Options "$@"
+
+### Utils #####################################################################
+
+handle_description() {
+   local name="$1"
+   local version="$2"
+
+   # Handle descriptions
+   description="$name/$version/Resources/Description"
+   if ! [ -e "$description" ]
+   then
+      mkdir -p $name/$version/Resources/
+      DescribeProgram -m ascii $name > "$description"
+      if [ `cat $description | wc -c` -eq 0 ]
+      then
+         rm $description
+         license=""
+         sourcedir="$compileSourcesDir/$(echo $name | tr '[:upper:]' '[:lower:]')-$version"
+         if [ ! -d "$sourcedir" ]
+         then
+            sourcedir="$compileSourcesDir/$name-$version"
+         fi
+         if [ -d "$sourcedir" ]
+         then
+            for licensefile in $sourcedir/COPYING* $sourcedir/LICENSE* $sourcedir/license*
+            do
+               if [ -e $licensefile ]
+               then
+                  md5license=`md5sum $licensefile | cut -d" " -f1`
+                  case "$md5license" in
+                  # GPL3
+                  f27defe1e96c2e1ecd4e0c9be8967949) newlicense="GNU General Public License version 3" ;;
+                  d32239bcb673463ab874e80d47fae504) newlicense="GNU General Public License version 3" ;;
+                  # GPL2 Mass Ave
+                  8ca43cbc842c2336e835926c2166c28b) newlicense="GNU General Public License version 2" ;;
+                  18810669f13b87348459e611d31ab760) newlicense="GNU General Public License version 2" ;;
+                  7975d4f2e1ca1e9df4dcfd94c6e1ae48) newlicense="GNU General Public License version 2" ;;
+                  cbbd794e2a0a289b9dfcc9f513d1996e) newlicense="GNU General Public License version 2" ;;
+                  e2ab865bd66f4d8e34f31582339c911a) newlicense="GNU General Public License version 2" ;;
+                  0278281246c1e59af1ef0ae1784a4948) newlicense="GNU General Public License version 2" ;;
+                  # GPL2 Franklin St mentions Library
+                  59530bdf33659b29e73d4adb9f9f6552) newlicense="GNU General Public License version 2" ;;
+                  751419260aa954499f7abaabaa882bbe) newlicense="GNU General Public License version 2" ;;
+                  eb723b61539feef013de476e68b5c50a) newlicense="GNU General Public License version 2" ;;
+                  a21edfd959813dc8af8161fe3f7ffaa2) newlicense="GNU General Public License version 2" ;;
+                  4325afd396febcb659c36b49533135d4) newlicense="GNU General Public License version 2" ;;
+                  eee1a5a93345d061765a5df481d19b7a) newlicense="GNU General Public License version 2" ;;
+                  6d5a9d4c4d3af25cd68fd83e8a8cb09c) newlicense="GNU General Public License version 2" ;;
+                  6ddd5335ef96fb858a138230af773710) newlicense="GNU General Public License version 2" ;;
+                  8ef380476f642c20ebf40fecb0add2ec) newlicense="GNU General Public License version 2" ;;
+                  9ea3144f04c41cd2eada5d3f472e6ea5) newlicense="GNU General Public License version 2" ;;
+                  892f569a555ba9c07a568a7c0c4fa63a) newlicense="GNU General Public License version 2" ;;
+                  # GPL2 Temple Place
+                  94d55d512a9ba36caa9b7df079bae19f) newlicense="GNU General Public License version 2" ;;
+                  393a5ca445f6965873eca0259a17f833) newlicense="GNU General Public License version 2" ;;
+                  fdafc691aa5fb7f8e2a9e9521fef771b) newlicense="GNU General Public License version 2" ;;
+                  0636e73ff0215e8d672dc4c32c317bb3) newlicense="GNU General Public License version 2" ;;
+                  a87895c4956801618eb9d3a4f8afe8f8) newlicense="GNU General Public License version 2" ;;
+                  c93c0550bd3173f4504b2cbd8991e50b) newlicense="GNU General Public License version 2" ;;
+                  5574c6965ae5f583e55880e397fbb018) newlicense="GNU General Public License version 2" ;;
+                  b0c80473f97008e42e29a9f80fcc55ff) newlicense="GNU General Public License version 2" ;;
+                  bae3019b4c6dc4138c217864bd04331f) newlicense="GNU General Public License version 2" ;;
+                  03b36fdd84f74b8d8189a202b980b67f) newlicense="GNU General Public License version 2" ;;
+                  7b0683f0a63b15f8cc8273f96fd564a9) newlicense="GNU General Public License version 2" ;;
+                  15fac19769be7c6091cda2f70757f064) newlicense="GNU General Public License version 2" ;;
+                  361b6b837cad26c6900a926b62aada5f) newlicense="GNU General Public License version 2" ;;
+                  878e3965c7b52d85827c75f5a2f3b314) newlicense="GNU General Public License version 2" ;;
+                  526c29250ae72f6933cdc01414b9943b) newlicense="GNU General Public License version 2" ;;
+                  9ac2e7cff1ddaf48b6eab6028f23ef88) newlicense="GNU General Public License version 2" ;;
+                  c46082167a314d785d012a244748d803) newlicense="GNU General Public License version 2" ;;
+                  # GPL2 Linux kernel
+                  d7810fab7487fb0aad327b76f1be7cd7) newlicense="GNU General Public License version 2" ;;
+                  # LGPL2 Mass Ave
+                  55ca817ccb7d5b5b66355690e9abc605) newlicense="GNU Library General Public License version 2" ;;
+                  ac4e4df3bbeacd481df543d2b12860b3) newlicense="GNU Library General Public License version 2" ;;
+                  252890d9eee26aab7b432e8b8a616475) newlicense="GNU Library General Public License version 2" ;;
+                  # LGPL2 Temple Place
+                  3bf50002aefd002f49e7bb854063f7e7) newlicense="GNU Library General Public License version 2" ;;
+                  7be2873b6270e45abacc503abbe2aa3d) newlicense="GNU Library General Public License version 2" ;;
+                  f30a9716ef3762e3467a2f62bf790f0a) newlicense="GNU Library General Public License version 2" ;;
+                  c46bda00ffbb0ba1dac22f8d087f54d9) newlicense="GNU Library General Public License version 2" ;;
+                  1e992216ed56a0fc1b6ea4a2de2962c7) newlicense="GNU Library General Public License version 2" ;;
+                  6e29c688d912da12b66b73e32b03d812) newlicense="GNU Library General Public License version 2" ;;
+                  # LGPL2.1
+                  fad9b3332be894bab9bc501572864b29) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  d7b37bf80a3df5a65b355433ae36d206) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  fbc093901857fcd118f065f900982c24) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  13b7ddb75583d236cf6855762f047e34) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  e3eda01d9815f8d24aae2dbd89b68b06) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  7fbc338309ac38fefcd64b04bb903e34) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  a049c5e22d3bd7bc3c9a2e9135a6d104) newlicense="GNU Lesser General Public License version 2.1" ;;
+                  # MPL1.1
+                  bfe1f75d606912a4111c90743d6c7325) newlicense="Mozilla Public License 1.1" ;;
+                  # Apache License 2.0
+                  218532c6a293a0aef9ab37fe496c3cd2) newlicense="Apache License 2.0" ;;
+                  *)
+                     Log_Terse "Could not autodetermine licensing for writing the Description file."
+                     Ask_Continue "Press Enter to view the license file $licensefile."
+                     ${PAGER:-less} $licensefile
+                     ;;
+                  esac # esac is ridiculous.
+                  if [ "$license" = "" ]
+                  then license="$newlicense"
+                  else license="$license, $newlicense"
+                  fi
+               fi
+            done
+         fi
+         if [ "$license" = "" ]
+         then license="***REPLACE THIS WITH THE NAME OF THE LICENSE***"
+         fi
+         if ! [ "$EDITOR" ] 
+         then
+            Log_Terse "EDITOR variable is not set. Can't edit description. Use \`export EDITOR='...'\` to set it."
+            return 0
+         fi
+cat <<EOF > $description
+[Name] $name
+[Summary] ***REPLACE THIS WITH A SHORT ONE LINE DESCRIPTION***
+[Description] ***REPLACE THIS WITH A MORE DETAILED DESCRIPTION***
+[License] $license
+[Homepage] ***REPLACE THIS WITH THE HOMEPAGE URL***
+EOF
+         $EDITOR $description
+         while grep -q "***REPLACE" $description
+         do
+            if Ask "Description wasn't filled properly. Retry?"
+            then $EDITOR $description
+            else
+               rm $description
+               return 1
+            fi
+         done
+      fi
+   fi
+   return 0
+}
 
 ### Operation #################################################################
 
-entry="$(Arg 1)"
-version="$(Arg 2)"
+# sets 'recipedir', 'program' and 'version'
+Set_Recipe_Program_And_Version_From_Args
 
-# Uncompress the file if it's a tarball
-if file $entry | grep -q bzip2
-then
-   entry=`Unpack_Archive $entry $compileLocalRecipesDir | cut -d/ -f1 | head -n 1`
-# Get path from LocalRecipes if only a name is given
-elif ! echo $entry | grep -q /
-then
-   entry=`ls "$compileLocalRecipesDir" | grep -i "^$(Arg 1)$"`
-   [ "$entry" ] || Die "Could not find $(Arg 1) in $compileLocalRecipesDir."
-   entry="$compileLocalRecipesDir/$entry"
-else
-   if [ -f "$entry/Recipe" ]
-   then
-      version=$(basename $entry)
-      entry=$(dirname $entry)
-   fi
-fi
+RecipeLint $program $version || Die "Recipe failed validation. Not submitting."
 
-cd $compileLocalRecipesDir
-[ -d "$entry" ] || Die "Could not read $entry."
+handle_description "$name" "$version"
 
-program=`basename $entry`
+[ -r "$recipedir/Resources/Description" ] || Die "No description file found. Not submitting."
 
-if ! [ "$version" ]
-then
-   [ `ls "$entry" | wc -l` -eq 1 ] || Die "Please specify a version for $program. Available versions are:\n$(ls $entry)"
-   version=`ls "$entry"`
-fi
-
-PackRecipe $program $version || Die "Recipe failed validation. Not submitting."
-[ -r "$entry/$version/Resources/Description" ] || Die "No description file found. Not submitting."
-
-[ -r "$entry/$version/Recipe" ] || Die "Could not read Recipe file in $entry/$version."
+[ -r "$recipedir/Recipe" ] || Die "Could not read Recipe file in $recipedir."
 
 # Perform some simple cleanups
-for i in `find $entry/$version -name Recipe`
+for i in `find $recipedir -name Recipe`
 do
   [ -w `dirname "$i"` ] || Die "Need write permissions to the recipe."
   sed -i.bak -e 's,$target/../Settings,$settings_target,g' \
@@ -85,69 +198,26 @@ do
   rm $i.bak
 done
 
-# Removes revisions from submitted recipes
-if echo "$version" | grep -q "\-r"
-then
-   newversion=`echo $version | sed 's,-r[0-9]*$,,'`
-   if [ -d "$program/$newversion" ]
-   then Die "Attempted to remove revision from $version but $program/$newversion is in the way."
-   fi
-   mv "$program/$version" "$program/$newversion"
-   version=$newversion
-fi
+cd "$recipedir"
+branch="submit-$program-$version"
+git pull
+git checkout -B "$branch"
+git add .
+git commit -m "$program $version"
 
-scriptsVersion=`Get_Version Scripts Current`
-compileVersion=`Get_Version Compile Current`
-mkdir temp-$$
-mkdir -p empty-$$/$program
-diff -urNa empty-$$/$program $program/$version>temp-$$/empty-patch
-base_recipe="$(FindPackage -l --type=recipe $program $version|grep -v LocalRecipes|head -n 1)"
-if ! [ "$base_recipe" ]
+if Boolean "gobo"
 then
-   base_recipe="$(FindPackage -l --type=recipe $program|grep -v LocalRecipes|head -n 1)"
-fi
-base=$(GetRecipe "$base_recipe")
-if [ -e "$base" ]
-then
-   # It's an updated version of an existing recipe
-   lastversion=$(basename $base)
-   echo "Generating diff from $lastversion->$version"
-   diff -urNa $base $program/$version>temp-$$/patch
+   git stash
+   cd "$compileRecipesDir"
+   git checkout "$compileUpstreamBranch" && \
+   git pull && \
+   git merge "submit-$program-$version" && \
+   git rebase && \
+   git push && \
+   git stash pop
+   git branch -D "submit-$program-$version"
 else
-   cp temp-$$/empty-patch temp-$$/patch
+   hub --version &> /dev/null || Die "You need to install 'hub' to auto-submit pull-requests"
+   hub pull-request -b "$compileUpstreamBranch" -h "submit-$program-$version" -m "$program $version"
 fi
 
-# Generate the report and save it to a file because wget requires that
-{
-   echo "ContributeRecipe protocol 1"
-   echo "Submitter: $compileRecipeAuthor"
-   echo "Program: $program"
-   echo "Version: $version"
-   echo "Compile: $compileVersion"
-   echo "Scripts: $scriptsVersion"
-   echo -n "GoboLinuxVersion: "
-   # GoboLinuxVersion had a newline on the end in some versions
-   # including 012, which corrupts the submission. Cut it off.
-   echo $(cat $goboSettings/GoboLinuxVersion)
-   echo "Origin: ${lastversion:-none}"
-   echo
-   cat temp-$$/empty-patch|base64
-   echo
-   cat temp-$$/patch|base64
-} > temp-$$/report
-
-if Boolean "pretend"
-then
-   cat temp-$$/report
-   echo
-   echo
-   echo "Submission report ends. Unencoded update patch follows."
-   cat temp-$$/patch
-elif ! wget -O - -q --post-file=temp-$$/report "$submissionTarget"
-then
-   Log_Error "There was an error using wget to submit your recipe."
-   Log_Error "This may be a temporary network problem or a firewall issue."
-   Log_Terse "Please check your internet connection and try again."
-fi
-
-rm -rf temp-$$ empty-$$
