Added experimental '--local-programs' option.

diff --git a/tools/ChrootCompile/bin/ChrootCompile b/tools/ChrootCompile/bin/ChrootCompile
--- a/tools/ChrootCompile/bin/ChrootCompile
+++ b/tools/ChrootCompile/bin/ChrootCompile
@@ -7,17 +7,6 @@ function die() {
 }
 
 #############################################################################
-# Verify our whereabouts
-#############################################################################
-if [ ! -d BaseDependencies ]
-then
-   if [ ! -z "`ls`" ]
-   then die "This doesn't look like a ChrootCompile environment directory. Rerun this script on an empty directory to build an environment."
-   fi
-   SetupChrootEnv
-fi
-
-#############################################################################
 # Setting options
 #############################################################################
 export goboPrograms="/Programs"
@@ -84,6 +73,13 @@ fi
 
 targetarch=$recipesubdir
 
+unset local_programs
+if [ "$1" == "--local-programs" -o "$1" == "-p" ]
+then
+    local_programs="$1"
+    shift
+fi
+
 unset verbose
 if [ "$1" == "--verbose" -o "$1" == "-v" ]
 then
@@ -98,8 +94,20 @@ then
     echo "Available options are:"
     echo "  -l, --local-repository:     use the repository at /Files/Compile (GoboLinux only)"
     echo "  -X, --cross-compile <arch>: cross-compile to 'arch' (GoboLinux only)"
+    echo "  -p, --local-programs:       get packages from /Programs (EXPERIMENTAL)"
     echo "  -v, --verbose:              verbose output"
     exit 0
+fi
+
+#############################################################################
+# Verify our whereabouts
+#############################################################################
+if [ ! -d BaseDependencies -a ! "$local_programs" ]
+then
+   if [ ! -z "`ls`" ]
+   then die "This doesn't look like a ChrootCompile environment directory. Rerun this script on an empty directory to build an environment."
+   fi
+   SetupChrootEnv
 fi
 
 #############################################################################
@@ -184,6 +192,7 @@ function cleanup() {
    do 
       unmount_dir $mp
    done
+   rmdir Archives 2> /dev/null
 }
 
 trap cleanup TERM STOP HUP EXIT
@@ -292,19 +301,23 @@ fi
 #############################################################################
 # Getting packages for BaseDependencies - Temporary only
 #############################################################################
+if [ ! "$local_programs" ]
+then
+   for arch in $hostarch $targetarch
+   do
+      [ -d Unpacked/$arch ] || mkdir -p Unpacked/$arch
+      [ -d Unpacked/$arch/_Checksums ] || mkdir -p Unpacked/$arch/_Checksums
+   done
+   [ -d BaseDependencies ] || mkdir BaseDependencies
 
-for arch in $hostarch $targetarch
-do
-   [ -d Unpacked/$arch ] || mkdir -p Unpacked/$arch
-   [ -d Unpacked/$arch/_Checksums ] || mkdir -p Unpacked/$arch/_Checksums
-done
+fi
 
-[ -d BaseDependencies ] || mkdir BaseDependencies
 [ -d $hostgetclean ] || mkdir -p $hostgetclean
 for dep in "${base_dependencies[@]}"
 do
    if ! ls BaseDependencies/$dep--* &> /dev/null && ! ls $hostgetclean/$dep--* &> /dev/null \
-   && ! [ -d BaseDependencies/$dep -o -d $hostgetclean/$dep ]
+   && ! [ -d BaseDependencies/$dep -o -d $hostgetclean/$dep ] \
+   && [ "$local_packages" -a ! -d "/Programs/$dep/Current/" ]
    then
       die "Package $dep, needed for bootstrap, was not found."
    fi
@@ -369,10 +382,15 @@ function load_dependency() {
    local dep="$1"
    local repositories="$2"
    local arch="$3"
-   local pkg=`get_package_for "$dep" "$repositories"`
-   [ ! "$pkg" ] && die "Dependency $dep could not be found."
-   unpacked=`unpack_package "$pkg" "$dep" "$arch"`
-
+   if [ "$local_programs" ]
+   then
+      unpacked="/Programs/$dep/Current/"
+      [ -d $unpacked ] || die "Dependency $dep could not be found."
+   else
+      local pkg=`get_package_for "$dep" "$repositories"`
+      [ ! "$pkg" ] && die "Dependency $dep could not be found."
+      unpacked=`unpack_package "$pkg" "$dep" "$arch"`
+   fi
    if [ $dep = $name ]
    then realcopy="--real-copy"
    else realcopy=""
