Failing when CreatePackage fails.

diff --git a/tools/ChrootCompile/bin/ChrootCompile b/tools/ChrootCompile/bin/ChrootCompile
--- a/tools/ChrootCompile/bin/ChrootCompile
+++ b/tools/ChrootCompile/bin/ChrootCompile
@@ -693,6 +693,7 @@ function in_target() {
 if [ "$chrootcompileMode" = "gobo" ]
 then
    package=`in_target in_chroot CreatePackage --no-sign --no-verify $name $version`
+   [ $? -ne 0 ] && die "Error on CreatePackage"
    mkdir -p $putclean
    cp -v $root/$name--$version* $putclean
 else
