Revamp checks for packages in Clean and Bootstrap

diff --git a/tools/ChrootCompile/ChrootCompile b/tools/ChrootCompile/ChrootCompile
--- a/tools/ChrootCompile/ChrootCompile
+++ b/tools/ChrootCompile/ChrootCompile
@@ -87,6 +87,12 @@ root=Area
 cleanup
 
 #sudo rm -rf $root
+if [ -d "$root" ]
+then
+   date=`date +%Y%m%d-%H%M`
+   echo "Backing up old $root to $root-old-$date."
+   sudo mv $root $root-old-$date
+fi
 
 mkdir -p $root
 mkdir -p $root/System/Links/Executables
@@ -136,20 +142,29 @@ ln -nfs /System/Links/Shared $root/usr/share
 
 cp -r Recipes $root/Files/Compile
 
+function filter_dir() {
+   grep -v Settings | grep -v Variable | grep -v Current
+}
+
 for dep in "${base_dependencies[@]}"
 do
-   [ `ls Clean/$dep--* 2> /dev=null | wc -l` -gt 1 ] && {
-      echo "More than one entry for $dep in Clean/ directory."
-      exit 1
-   } || true
-   [ `ls Bootstrap/$dep--* 2> /dev/null | wc -l` -gt 1 ] && {
-      echo "More than one entry for $dep in Bootstrap/ directory."
-      exit 1
-   } || true
-   pkg=`ls Clean/$dep--* 2> /dev/null || true`
-   [ ! "$pkg" ] && pkg=`ls Bootstrap/$dep--* 2> /dev/null | head -n 1`
+   pkg=
+   for repo in Clean Bootstrap
+   do
+      [ `ls $repo/$dep--* 2> /dev/null | wc -l` -gt 1 ] && {
+         echo "More than one entry for $dep in $repo/ directory."
+         exit 1
+      } || true
+      [ `ls $repo/$dep 2> /dev/null | filter_dir | wc -l` -gt 1 ] && {
+         echo "More than one entry for $dep in $repo/ directory."
+         exit 1
+      } || true
+      pkg=`ls -d $repo/$dep/* 2> /dev/null | filter_dir || true`
+      [ ! "$pkg" ] && pkg=`ls $repo/$dep--* 2> /dev/null || true`
+      [ "$pkg" ] && break
+   done
    [ ! "$pkg" ] && {
-      echo "Base dependency $dep could not be filled."
+      echo "Base dependency $dep could not be found."
       exit 1
    }
    sudo $(dirname $0)/MiniInstallPackage "$pkg" "$root"
diff --git a/tools/ChrootCompile/MiniInstallPackage b/tools/ChrootCompile/MiniInstallPackage
--- a/tools/ChrootCompile/MiniInstallPackage
+++ b/tools/ChrootCompile/MiniInstallPackage
@@ -8,26 +8,40 @@ goboPrograms=/Programs
    exit 1
 } 
 
-package=`readlink -f "$1"`
-root="$2"
+if [ -d "$1" ] 
+then
+   dir=`readlink -f "$1"`
+   version=$(basename $dir)
+echo VERSION $version
+   name=$(basename `dirname $dir`)
+echo NAME $name
+   unpacked=$(dirname $dir)
+else
+   package=`readlink -f "$1"`
+   base=$(basename $package)
+   name=${base%%--*}
+   version=${base#*--}
+   version=${version%%--*}
+   unpacked=$(dirname $package)/$name
+   if ! [ -d "$unpacked" ]
+   then
+      pushd $(dirname $package) &> /dev/null
+      tar xjpf "$package"
+      popd &> /dev/null
+   fi
+fi
 
-base=$(basename $package)
-name=${base%%--*}
-version=${base#*--}
-version=${version%%--*}
+if ! [ -d "$unpacked" ]
+then
+   echo "MiniInstallPackage: error - directory $unpacked does not exist."
+   exit 1
+fi
+
+root="$2"
 
 echo "Installing $name version $version..."
 
 pushd "$root/$goboPrograms" &> /dev/null
-unpacked=$(dirname $package)/$name
-if ! [ -d "$unpacked" ]
-then
-   pushd $(dirname $package) &> /dev/null
-   tar xjpf "$package"
-   popd &> /dev/null
-fi
-
-#cp -R "$unpacked" .
 mkdir -p "$name"
 mount --bind "$unpacked" "$name"
 [ `ls "$name" | grep -v Settings | grep -v Variable | grep -v Current | wc -l` -gt 1 ] && {
