Become a little more stubborn.

diff --git a/tools/ChrootCompile/ChrootCompile b/tools/ChrootCompile/ChrootCompile
--- a/tools/ChrootCompile/ChrootCompile
+++ b/tools/ChrootCompile/ChrootCompile
@@ -68,8 +68,8 @@ base_dependencies=(
      "PCRE" # needed by Grep
     "Grep" # needed by Scripts
     "Python" # needed by Scripts
-     "OpenSSL" # needed by Wget
-    "Wget" # needed by Compile
+#     "OpenSSL" # needed by Wget
+#    "Wget" # needed by Compile
     "Gawk" # needed by Compile
     "FindUtils" # needed by Compile (find)
      "Bzip2" # needed by Atool
@@ -82,8 +82,8 @@ base_dependencies=(
     "MkTemp" # needed by Scripts
     "Mtail" # needed by Scripts
     "BinUtils" # needed by GCC (as)
-#    "Linux" # needed by GCC (include/linux)
-    "Linux-Libc-Headers" # instead of Linux
+    "Linux" # needed by GCC (include/linux)
+#    "Linux-Libc-Headers" # instead of Linux
    "GCC"
     "Sudo" # needed by Scripts
     "Make" # needed by Compile
@@ -104,11 +104,9 @@ then
    recipedir="$1"
    name=$(basename $(dirname $recipedir))
    version=$(basename $recipedir)
-   #echo "Expected recipe directory as a parameter (example: Recipes/Bash/3.0)"
-   #exit 1
-else 
-   name=$1
-   version=$2
+else
+   echo "Expected recipe directory as a parameter (example: Recipes/Bash/3.0)"
+   exit 1
 fi
 
 
@@ -220,14 +218,14 @@ do
    if ! ls Bootstrap/$dep--* &> /dev/null && ! ls Clean/$dep--* &> /dev/null && ! ls LocalPackages/$dep--* &> /dev/null \
    && ! [ -d Bootstrap/$dep -o -d Clean/$dep -o -d LocalPackages/$dep ]
    then
-      if [ -e /System/Settings/gobo ]
-      then
-         echo "Warning: Could not find $dep in ./{LocalPackages,Bootstrap,Clean}. Creating package based on host system"
-         cd Bootstrap; CreatePackage --no-verify --no-sign $dep; cd - &> /dev/null
-      else
+#      if [ -e /System/Settings/gobo ]
+#      then
+#         echo "Warning: Could not find $dep in ./{LocalPackages,Bootstrap,Clean}. Creating package based on host system"
+#         cd Bootstrap; CreatePackage --no-verify --no-sign $dep; cd - &> /dev/null
+#      else
          echo "Package $dep, needed for bootstrap, was not found."
          exit 1
-      fi
+#      fi
    fi
 done
 
@@ -406,4 +404,4 @@ sudo chroot $root ./GenericInstall --no-web $name "$version" recipe
 #############################################################################
 package=`sudo chroot $root CreatePackage --no-sign --no-verify $name $version`
 mkdir -p $scriptdir/Clean
-cp $root/$package $scriptdir/Clean
+cp $root/$name--$version* $scriptdir/Clean
