The test [ ! -e ] will evaluate to false if the file already exists, making the 'die' command at the end of the block to be executed.

diff --git a/tools/ChrootCompile/ChrootCompile b/tools/ChrootCompile/ChrootCompile
--- a/tools/ChrootCompile/ChrootCompile
+++ b/tools/ChrootCompile/ChrootCompile
@@ -515,14 +515,14 @@ function fetch_archive_off_recipe() {
          if [ "$url" ]
          then
             file=`basename "$url"`
-            [ ! -e "$file" ] && { wget -c "$url" || die "Couldn't fetch $url" ;}
+            [ ! -e "$file" ] && { wget -c "$url" || die "Couldn't fetch $url" ;} || true
          fi
          if [ "${urls[*]}" ]
          then
             for url in "${urls[@]}"
             do
                file=`basename "$url"`
-               [ ! -e "$file" ] && { wget -c "$url" || die "Couldn't fetch $url" ;}
+               [ ! -e "$file" ] && { wget -c "$url" || die "Couldn't fetch $url" ;} || true
             done
          fi
       fi
