Improve sanity checks in scripts; use Linux-Libc-Headers

diff --git a/tools/ChrootCompile/ChrootCompile b/tools/ChrootCompile/ChrootCompile
--- a/tools/ChrootCompile/ChrootCompile
+++ b/tools/ChrootCompile/ChrootCompile
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -e
 
 CompileConfDir=/System/Settings/Compile
 
@@ -20,15 +20,15 @@ base_dependencies=(
    "Glibc"
     "Ncurses" # needed by Bash
     "Readline" # needed by Bash
-    "GPM" # needed by Bash (FIXME)
+#    "GPM" # needed by Bash (FIXME)
    "Bash"
     "CoreUtils" # needed by Scripts (cp...)
     "Sed" # needed by Scripts
      "PCRE" # needed by Grep
     "Grep" # needed by Scripts
     "Python" # needed by Scripts
-     "OpenSSL" # needed by Wget
-    "Wget" # needed by Compile
+#     "OpenSSL" # needed by Wget
+#    "Wget" # needed by Compile
     "Gawk" # needed by Compile
     "FindUtils" # needed by Compile (find)
      "Bzip2" # needed by Atool
@@ -41,7 +41,8 @@ base_dependencies=(
     "MkTemp" # needed by Scripts
     "Mtail" # needed by Scripts
     "BinUtils" # needed by GCC (as)
-    "Linux" # needed by GCC (include/linux)
+#    "Linux" # needed by GCC (include/linux)
+    "Linux-Libc-Headers" # instead of Linux
    "GCC"
     "Sudo" # needed by Scripts
     "Make" # needed by Compile
@@ -69,11 +70,11 @@ echo "ChrootCompile: Compiling $name $version..."
 
 cleanup() {
    echo "ChrootCompile: Will unmount /dev..."
-   sudo umount $root/System/Kernel/Devices
+   sudo umount $root/System/Kernel/Devices || true
    echo "ChrootCompile: Will unmount /proc..."
-   sudo umount $root/System/Kernel/Status
+   sudo umount $root/System/Kernel/Status || true
    echo "ChrootCompile: Will unmount Archives..."
-   sudo umount $root/Files/Compile/Archives
+   sudo umount $root/Files/Compile/Archives || true
    mount | grep "$root" | awk '{ print $1 }' | while read mp
    do 
       echo "ChrootCompile: Will unmount $mp..."
@@ -81,11 +82,11 @@ cleanup() {
    done
 }
 
-cleanup
-
 root=Area
 
-sudo rm -rf $root
+cleanup
+
+#sudo rm -rf $root
 
 mkdir -p $root
 mkdir -p $root/System/Links/Executables
@@ -137,8 +138,20 @@ cp -r Recipes $root/Files/Compile
 
 for dep in "${base_dependencies[@]}"
 do
-   pkg=`ls Clean/$dep--* 2> /dev/null | head -n 1`
+   [ `ls Clean/$dep--* 2> /dev=null | wc -l` -gt 1 ] && {
+      echo "More than one entry for $dep in Clean/ directory."
+      exit 1
+   } || true
+   [ `ls Bootstrap/$dep--* 2> /dev/null | wc -l` -gt 1 ] && {
+      echo "More than one entry for $dep in Bootstrap/ directory."
+      exit 1
+   } || true
+   pkg=`ls Clean/$dep--* 2> /dev/null || true`
    [ ! "$pkg" ] && pkg=`ls Bootstrap/$dep--* 2> /dev/null | head -n 1`
+   [ ! "$pkg" ] && {
+      echo "Base dependency $dep could not be filled."
+      exit 1
+   }
    sudo MiniInstallPackage "$pkg" "$root"
 done
 
@@ -204,6 +217,8 @@ trap cleanup TERM STOP HUP EXIT
       done
    fi
 )
+
+export LD_LIBRARY_PATH=/System/Links/Libraries
 
 echo "ChrootCompile: Will run ldconfig..."
 sudo chroot $root ldconfig
