Avoid questions when no recipe/package could be found for a given depedency.

diff --git a/tools/Scripts/bin/CheckDependencies b/tools/Scripts/bin/CheckDependencies
--- a/tools/Scripts/bin/CheckDependencies
+++ b/tools/Scripts/bin/CheckDependencies
@@ -265,6 +265,17 @@ def ask_if_install(match) :
 	else :
 		reason = p + " is not installed."
 
+	if t == None :
+		os.system('''
+. ScriptFunctions
+Import Log
+export scriptName=CheckDependencies
+echo >&2
+Log_Terse "%s"
+Log_Terse "Unable to fulfill the dependency."
+'''%(reason))
+		return
+
 	if global_always_do :
 		if global_always_do=='install/compile' :
 			if t == 'recipe' :
