Functions/Compile: Added missing import. This doesn't fix anything, the fact that it was missing just came up during testing. Functions/GoboLinux: GetArchitecture binary compatiblity changes. It's been on the -devel list for a couple of days, and nobody's objected. ColorMake: Now falls back to normal non-colorful behavior if mtail is not installed. Before, it would just fail with a "file not found" error.

diff --git a/tools/Scripts/bin/ColorMake b/tools/Scripts/bin/ColorMake
--- a/tools/Scripts/bin/ColorMake
+++ b/tools/Scripts/bin/ColorMake
@@ -3,6 +3,7 @@
 . ScriptFunctions
 Import File
 Import GoboLinux
+Import Process
 
 # XXX "Real vs. rootless" support
 if [ -x /bin/make ]
@@ -20,11 +21,16 @@ done
 
 workaround=`Temporary_File`
 
-{ $makecmd "$@" 2>&1
-  echo $? > $workaround
-} | mtail --config="`Find_Conf ColorMake.mtailrc`" -q
+if Quiet which mtail; then
+   { $makecmd "$@" 2>&1
+     echo $? > $workaround
+   } | mtail --config="`Find_Conf ColorMake.mtailrc`" -q
 
-returnvalue=`cat $workaround`
-rm -- $workaround
+   returnvalue=`cat $workaround`
+   rm -- $workaround
 
-exit $returnvalue
+   exit $returnvalue
+else
+   Log_Terse "mtail not found. Unable to colorize output."
+   $makecmd "$@"
+fi
