Fixed \t characters.

diff --git a/tools/Scripts/bin/CreateRootlessEnvironment b/tools/Scripts/bin/CreateRootlessEnvironment
--- a/tools/Scripts/bin/CreateRootlessEnvironment
+++ b/tools/Scripts/bin/CreateRootlessEnvironment
@@ -8,9 +8,9 @@
 
 CURRENT_SCRIPTS_VERSION= # This variable is automatically set by Make
 hostSystemDependencies=(
-	sh mv cp ls find sed grep
-	python
-	seq
+   sh mv cp ls find sed grep
+   python
+   seq
 )
 
 
@@ -20,11 +20,11 @@ hostSystemDependencies=(
 
 if [ "$1" = "--help" -o  "$1" = "-help" -o "$1" = "-h" ] 
 then
-	echo "GoboLinux Rootless environment creation script"
-	echo "Copyright (C) Andre Detsch, 2004-2005 - Released under the GNU GPL."
-	echo "Usage: $0 [<prefix>]"
-	echo "Default prefix is ${HOME}"
-	exit 1
+   echo "GoboLinux Rootless environment creation script"
+   echo "Copyright (C) Andre Detsch, 2004-2005 - Released under the GNU GPL."
+   echo "Usage: $0 [<prefix>]"
+   echo "Default prefix is ${HOME}"
+   exit 1
 fi
 
 
@@ -40,10 +40,10 @@ then
 fi
 
 for app in "${hostSystemDependencies[@]}"; do
-	if [ ! "`which "$app"`" ]; then
-		echo "For Rootless GoboLinux requires $app."
-		echo 1
-	fi
+   if [ ! "`which "$app"`" ]; then
+      echo "For Rootless GoboLinux requires $app."
+      echo 1
+   fi
 done
 
 
@@ -56,9 +56,9 @@ done
 # default goboPrefix is ${HOME}
 if [ "$1" ] 
 then
-	export goboPrefix="$1"
+   export goboPrefix="$1"
 else
-	export goboPrefix=${HOME}
+   export goboPrefix=${HOME}
 fi
 
 # Saves the current directory for latter restoration
@@ -96,7 +96,7 @@ System/Links/Tasks \
 System/Settings \
 System/Variable
 do
-	[ -e "${goboPrefix}/$dir" ] || { echo "Creating ${goboPrefix}/$dir"; mkdir -p "${goboPrefix}/$dir"; }
+   [ -e "${goboPrefix}/$dir" ] || { echo "Creating ${goboPrefix}/$dir"; mkdir -p "${goboPrefix}/$dir"; }
 done
 
 # Rootless uses /tmp as tmp directory
@@ -142,23 +142,23 @@ export PYTHONPATH=${goboPrefix}/System/Links/Libraries/python2.3/site-packages:$
 # preparing a real_install (which is wrapped by Scripts install)...
 if [ ! "`which real_install`" ] 
 then
-	if [ -e "/bin/install" ]
-	then
-		ln -sfn /bin/install ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
-	elif [ -e "/usr/bin/install" ]
-	then
-		ln -sfn /usr/bin/install ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
-	else 
-		i=`which install`
-		g=`file "$i" | grep ELF`
-		if [ "$g" ]
-		then
-			ln -sfn "$i" ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
-		else
-			echo Warning: no CoreUtils install binary was found. Please provide it and link it 
-			echo at ${goboPrefix}/Programs/Rootless/1.0/bin/real_install  
-		fi
-	fi
+   if [ -e "/bin/install" ]
+   then
+      ln -sfn /bin/install ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
+   elif [ -e "/usr/bin/install" ]
+   then
+      ln -sfn /usr/bin/install ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
+   else 
+      i=`which install`
+      g=`file "$i" | grep ELF`
+      if [ "$g" ]
+      then
+         ln -sfn "$i" ${goboPrefix}/Programs/Rootless/1.0/bin/real_install
+      else
+         echo Warning: no CoreUtils install binary was found. Please provide it and link it 
+         echo at ${goboPrefix}/Programs/Rootless/1.0/bin/real_install  
+      fi
+   fi
 fi
 
 
@@ -169,48 +169,48 @@ fi
 
 if [ ! -e "${goboPrefix}/Programs/Scripts/Current" ]
 then 
-	if [ -e "/Programs/Scripts/Current" ]
-	then
-		echo "You are under a GoboLinux system. Copying the Scripts package to your Rootless "
-		echo "tree is not required, but its recommended if you want to change some settings."
-		echo "Anytime latter you can run 'InstallPackage Scripts' in order to install the "
-		echo "latests Scripts version inside Rootless."
-		echo "Would you like to copy /Program/Scripts to ${goboPrefix}/Programs/Scripts? [y]es/[N]o"
-		read
-		if [ "$REPLY" = "y" ]
-		then
-			scripts=`readlink -f /Programs/Scripts/Current`
-			mkdir ${goboPrefix}/Programs/Scripts
-			cp -r $scripts ${goboPrefix}/Programs/Scripts
-			cd ${goboPrefix}/Programs/Scripts
-			ln -s `basename ${scripts}` Current
-		fi
-	else
-		version="${CURRENT_SCRIPTS_VERSION:-2.4.2}"
-		scripts=Scripts--${version}--i686.tar.bz2
-		wget http://kundor.org/gobo/packages/official/${scripts} -O /tmp/${scripts}
-		cd ${goboPrefix}/Programs/
-		tar xvfj /tmp/${scripts}
-		cd Scripts
-		ln -sfn $version Current
-		cp -R ${goboPrefix}/Programs/Scripts/$version/Resources/Defaults/Settings ${goboPrefix}/Programs/Scripts/Settings
-	fi
+   if [ -e "/Programs/Scripts/Current" ]
+   then
+      echo "You are under a GoboLinux system. Copying the Scripts package to your Rootless "
+      echo "tree is not required, but its recommended if you want to change some settings."
+      echo "Anytime latter you can run 'InstallPackage Scripts' in order to install the "
+      echo "latests Scripts version inside Rootless."
+      echo "Would you like to copy /Program/Scripts to ${goboPrefix}/Programs/Scripts? [y]es/[N]o"
+      read
+      if [ "$REPLY" = "y" ]
+      then
+         scripts=`readlink -f /Programs/Scripts/Current`
+         mkdir ${goboPrefix}/Programs/Scripts
+         cp -r $scripts ${goboPrefix}/Programs/Scripts
+         cd ${goboPrefix}/Programs/Scripts
+         ln -s `basename ${scripts}` Current
+      fi
+   else
+      version="${CURRENT_SCRIPTS_VERSION:-2.4.2}"
+      scripts=Scripts--${version}--i686.tar.bz2
+      wget http://kundor.org/gobo/packages/official/${scripts} -O /tmp/${scripts}
+      cd ${goboPrefix}/Programs/
+      tar xvfj /tmp/${scripts}
+      cd Scripts
+      ln -sfn $version Current
+      cp -R ${goboPrefix}/Programs/Scripts/$version/Resources/Defaults/Settings ${goboPrefix}/Programs/Scripts/Settings
+   fi
 fi
 
 function link_directory() {
-	from="$1"
-	to="$2"
-	cd "${to}"
-	for entry in ${from}/*; do ln -sfn ${entry} . 2> /dev/null; done
-	cd - > /dev/null
+   from="$1"
+   to="$2"
+   cd "${to}"
+   for entry in ${from}/*; do ln -sfn ${entry} . 2> /dev/null; done
+   cd - > /dev/null
 }
 
 
 if [ -e "${goboPrefix}/Programs/Scripts/Current" ]
 then
-	echo Pre-linking Scripts...
-	link_directory ../../Programs/Scripts/Settings       ${goboPrefix}/System/Settings
-	link_directory ../../../Programs/Scripts/Current/bin ${goboPrefix}/System/Links/Executables
+   echo Pre-linking Scripts...
+   link_directory ../../Programs/Scripts/Settings       ${goboPrefix}/System/Settings
+   link_directory ../../../Programs/Scripts/Current/bin ${goboPrefix}/System/Links/Executables
 fi
 
 
@@ -235,21 +235,21 @@ Log_Normal "Gobo Rootless i686 has been installed."
 
 # Function to remove things in a pretty way
 function rootless_remove() {
-	while [ "$1" ]; do
-		Log_Normal "Removing $1"
-		rm -rf "$1"
-		shift
-	done
+   while [ "$1" ]; do
+      Log_Normal "Removing $1"
+      rm -rf "$1"
+      shift
+   done
 }
 
 # Function to remove all the stuff created by this script
 function rootless_uninstall() {
-	if Ask "Cancel rootless installation?"; then
-		cd "${HOME}"
-		rootless_remove "${goboPrograms}" "${goboPrefix}/System" "${goboSettings}"
-		[ -e "/Programs/Scripts/Current" ] || rootless_remove "${HOME}/.Settings"
-		exit 1
-	fi
+   if Ask "Cancel rootless installation?"; then
+      cd "${HOME}"
+      rootless_remove "${goboPrograms}" "${goboPrefix}/System" "${goboSettings}"
+      [ -e "/Programs/Scripts/Current" ] || rootless_remove "${HOME}/.Settings"
+      exit 1
+   fi
 }
 
 ###############################################################################
@@ -257,43 +257,43 @@ function rootless_uninstall() {
 ###############################################################################
 binaries_ok="no"
 if [ "`Get_Architecture`" != i686 ]; then
-	Log_Terse "Your machine is `Get_Architecture`."
-	if ! Quiet which gcc; then
-		Log_Error "gcc isn't installed. Can't recompile"
-		binaries_ok="no"
-	elif ! Quiet which make; then
-		Log_Error "make isn't installed. Can't recompile"
-	elif [ -d "${goboPrograms}/Scripts/Current" ]; then
-		if Ask "Recompile binaries for your system?"; then
-			Quiet pushd "${goboPrograms}/Scripts/Current"
-			# Temporarily create a header file to be used as a last resort if the
-			# real one doesn't exist on the host system.
-			mkdir -p .fakeheaders/linux
-			echo -n '
-				#ifndef _LINUX_KDEV_T_H
-				#define _LINUX_KDEV_T_H
-				#define MAJOR(dev)      ((dev)>>8)
-				#define MINOR(dev)      ((dev) & 0xff)
-				#define MKDEV(ma,mi)    ((ma)<<8 | (mi))
-				#endif
-			' >> .fakeheaders/linux/kdev_t.h
-			old_include_path="${C_INCLUDE_PATH}"
-			location_of_fake_kdev="${goboPrograms}/Scripts/Current/.fakeheaders"
-			export C_INCLUDE_PATH="${C_INCLUDE_PATH}:$location_of_fake_kdev"
-			make cleanup && make && binaries_ok="yes"
-			[ "$binaries_ok" == "yes" ] || Log_Error "Build Failed"
-			export C_INCLUDE_PATH="${old_include_path}"
-			rm -rf .fakeheaders
-			Quiet popd	
-		fi
-	fi
+   Log_Terse "Your machine is `Get_Architecture`."
+   if ! Quiet which gcc; then
+      Log_Error "gcc isn't installed. Can't recompile"
+      binaries_ok="no"
+   elif ! Quiet which make; then
+      Log_Error "make isn't installed. Can't recompile"
+   elif [ -d "${goboPrograms}/Scripts/Current" ]; then
+      if Ask "Recompile binaries for your system?"; then
+         Quiet pushd "${goboPrograms}/Scripts/Current"
+         # Temporarily create a header file to be used as a last resort if the
+         # real one doesn't exist on the host system.
+         mkdir -p .fakeheaders/linux
+         echo -n '
+            #ifndef _LINUX_KDEV_T_H
+            #define _LINUX_KDEV_T_H
+            #define MAJOR(dev)      ((dev)>>8)
+            #define MINOR(dev)      ((dev) & 0xff)
+            #define MKDEV(ma,mi)    ((ma)<<8 | (mi))
+            #endif
+         ' >> .fakeheaders/linux/kdev_t.h
+         old_include_path="${C_INCLUDE_PATH}"
+         location_of_fake_kdev="${goboPrograms}/Scripts/Current/.fakeheaders"
+         export C_INCLUDE_PATH="${C_INCLUDE_PATH}:$location_of_fake_kdev"
+         make cleanup && make && binaries_ok="yes"
+         [ "$binaries_ok" == "yes" ] || Log_Error "Build Failed"
+         export C_INCLUDE_PATH="${old_include_path}"
+         rm -rf .fakeheaders
+         Quiet popd  
+      fi
+   fi
 else
-	binaries_ok="yes"
+   binaries_ok="yes"
 fi
 
 if [ "$binaries_ok" != "yes" ]; then
-	Log_Error "Rootless probably won't work here."
-	echo -n "Rootless GoboLinux consists mostly of cross-platform shell scripts, but it does
+   Log_Error "Rootless probably won't work here."
+   echo -n "Rootless GoboLinux consists mostly of cross-platform shell scripts, but it does
 include a couple of binary (compiled) programs. If you're seeing this message,
 the versions of those programs currently installed were built for a different
 type of computer (an i686 with a GNU Linux kernel).
@@ -303,7 +303,7 @@ Compatibility (as do some variants of BSD), everything may work anyway, but
 you're probably best off reporting this to the gobolinux-users mailing list,
 and removing Rootless for the time being.
 "
-	rootless_uninstall
+   rootless_uninstall
 fi
 
 ###############################################################################
@@ -312,12 +312,12 @@ fi
 
 if [ -e "${goboPrefix}/Programs/Scripts/Current" ] 
 then
-	Log_Normal Linking Scripts...
-	UpdateSettings Scripts
-	SymlinkProgram Scripts
+   Log_Normal Linking Scripts...
+   UpdateSettings Scripts
+   SymlinkProgram Scripts
 elif [ ! -e "/Programs/Scripts/Current" ]; then
-	Log_Error "Installation failed"
-	rootless_uninstall
+   Log_Error "Installation failed"
+   rootless_uninstall
 fi
 
 echo
@@ -331,15 +331,15 @@ SymlinkProgram Rootless
 
 for f in .bash_profile .zshrc
 do
-	file="${HOME}/${f}"
-	line=". ${goboPrefix}/Programs/Rootless/Current/bin/StartRootless"
-	
-	if ! grep "^${line}" ${file} &> /dev/null
-	then
-		Log_Normal "Adding StartRootless line to ~/${f}"
-		echo >> ${file}
-		echo "$line" >> ${file}
-	fi
+   file="${HOME}/${f}"
+   line=". ${goboPrefix}/Programs/Rootless/Current/bin/StartRootless"
+   
+   if ! grep "^${line}" ${file} &> /dev/null
+   then
+      Log_Normal "Adding StartRootless line to ~/${f}"
+      echo >> ${file}
+      echo "$line" >> ${file}
+   fi
 done
 
 # Restores the last directory
