Changes are described on gobolinux-devel:
http://lists.gobolinux.org/pipermail/gobolinux-devel/2006-September/001590.html

diff --git a/tools/Scripts/bin/CreateRootlessEnvironment b/tools/Scripts/bin/CreateRootlessEnvironment
--- a/tools/Scripts/bin/CreateRootlessEnvironment
+++ b/tools/Scripts/bin/CreateRootlessEnvironment
@@ -1,17 +1,24 @@
 #!/bin/sh
-
 #####################################################################
 #
-# CreateRootlessEnvironment, almost stable
-# Andre Detsch, Renato Costa
-# 
+# CreateRootlessEnvironment
+# Andre Detsch, Renato Costa, Dan
+#
 #####################################################################
+
+CURRENT_SCRIPTS_VERSION= # This variable is automatically set by Make
+hostSystemDependencies=(
+	sh mv cp ls find sed grep
+	python
+	seq
+)
+
 
 ###############################################################################
 # help message on $1 == --help
 ###############################################################################
 
-if [ "$1" = "--help" -o  "$1" = "-help" ] 
+if [ "$1" = "--help" -o  "$1" = "-help" -o "$1" = "-h" ] 
 then
 	echo "GoboLinux Rootless environment creation script"
 	echo "Copyright (C) Andre Detsch, 2004-2005 - Released under the GNU GPL."
@@ -22,7 +29,7 @@ fi
 
 
 ###############################################################################
-# Checking for required tools (only wget, I guess)
+# Checking for required tools
 ###############################################################################
 
 # Note: wget is not required when running on a GoboLinux box
@@ -31,6 +38,13 @@ then
     echo "Please install wget in order to run this script."
     exit 1
 fi
+
+for app in "${hostSystemDependencies[@]}"; do
+	if [ ! "`which "$app"`" ]; then
+		echo "For Rootless GoboLinux requires $app."
+		echo 1
+	fi
+done
 
 
 ###############################################################################
@@ -110,11 +124,11 @@ alias SymlinkProgram="SymlinkProgram --relative"
 
 [ ! "$goboPrefix" ] && export goboPrefix='$rootlessPrefix'
 
-if [ ${ZSH_NAME} = "zsh" ]
+if [ "${ZSH_NAME}" = "zsh" ]
 then
    [ -e "${goboPrefix}/System/Settings/zshrc" ] && . "${goboPrefix}/System/Settings/zshrc"
    prompt lode cyan
-elif [ ${SHELL} = "/bin/bash" ]
+elif [ "${SHELL}" = "/bin/bash" ]
 then
    [ -e "${goboPrefix}/System/Settings/bashrc" ] && . "${goboPrefix}/System/Settings/bashrc"
 fi
@@ -172,14 +186,14 @@ then
 			ln -s `basename ${scripts}` Current
 		fi
 	else
-		version=2.3.1
+		version="${CURRENT_SCRIPTS_VERSION:-2.4.2}"
 		scripts=Scripts--${version}--i686.tar.bz2
 		wget http://kundor.org/gobo/packages/official/${scripts} -O /tmp/${scripts}
 		cd ${goboPrefix}/Programs/
 		tar xvfj /tmp/${scripts}
 		cd Scripts
 		ln -sfn $version Current
-		cp -a ${goboPrefix}/Programs/Scripts/$version/Resources/Defaults/Settings ${goboPrefix}/Programs/Scripts/
+		cp -R ${goboPrefix}/Programs/Scripts/$version/Resources/Defaults/Settings ${goboPrefix}/Programs/Scripts/Settings
 	fi
 fi
 
@@ -190,6 +204,7 @@ function link_directory() {
 	for entry in ${from}/*; do ln -sfn ${entry} . 2> /dev/null; done
 	cd - > /dev/null
 }
+
 
 if [ -e "${goboPrefix}/Programs/Scripts/Current" ]
 then
@@ -207,18 +222,106 @@ fi
 
 
 ###############################################################################
+# Load all those beautiful shell script libraries we know and love
+###############################################################################
+
+echo "Accessing new Rootless environment"
+PATH="${PATH}:${goboPrefix}/Programs/Scripts/Current/bin/"
+. ScriptFunctions
+Import Log
+Import GoboLinux
+Import Process
+Log_Normal "Gobo Rootless i686 has been installed."
+
+# Function to remove things in a pretty way
+function rootless_remove() {
+	while [ "$1" ]; do
+		Log_Normal "Removing $1"
+		rm -rf "$1"
+		shift
+	done
+}
+
+# Function to remove all the stuff created by this script
+function rootless_uninstall() {
+	if Ask "Cancel rootless installation?"; then
+		cd "${HOME}"
+		rootless_remove "${goboPrograms}" "${goboPrefix}/System" "${goboSettings}"
+		[ -e "/Programs/Scripts/Current" ] || rootless_remove "${HOME}/.Settings"
+		exit 1
+	fi
+}
+
+###############################################################################
+# Check whether we need to recompile anything
+###############################################################################
+binaries_ok="no"
+if [ "`Get_Architecture`" != i686 ]; then
+	Log_Terse "Your machine is `Get_Architecture`."
+	if ! Quiet which gcc; then
+		Log_Error "gcc isn't installed. Can't recompile"
+		binaries_ok="no"
+	elif ! Quiet which make; then
+		Log_Error "make isn't installed. Can't recompile"
+	elif [ -d "${goboPrograms}/Scripts/Current" ]; then
+		if Ask "Recompile binaries for your system?"; then
+			Quiet pushd "${goboPrograms}/Scripts/Current"
+			# Temporarily create a header file to be used as a last resort if the
+			# real one doesn't exist on the host system.
+			mkdir -p .fakeheaders/linux
+			echo -n '
+				#ifndef _LINUX_KDEV_T_H
+				#define _LINUX_KDEV_T_H
+				#define MAJOR(dev)      ((dev)>>8)
+				#define MINOR(dev)      ((dev) & 0xff)
+				#define MKDEV(ma,mi)    ((ma)<<8 | (mi))
+				#endif
+			' >> .fakeheaders/linux/kdev_t.h
+			old_include_path="${C_INCLUDE_PATH}"
+			location_of_fake_kdev="${goboPrograms}/Scripts/Current/.fakeheaders"
+			export C_INCLUDE_PATH="${C_INCLUDE_PATH}:$location_of_fake_kdev"
+			make cleanup && make && binaries_ok="yes"
+			[ "$binaries_ok" == "yes" ] || Log_Error "Build Failed"
+			export C_INCLUDE_PATH="${old_include_path}"
+			rm -rf .fakeheaders
+			Quiet popd	
+		fi
+	fi
+else
+	binaries_ok="yes"
+fi
+
+if [ "$binaries_ok" != "yes" ]; then
+	Log_Error "Rootless probably won't work here."
+	echo -n "Rootless GoboLinux consists mostly of cross-platform shell scripts, but it does
+include a couple of binary (compiled) programs. If you're seeing this message,
+the versions of those programs currently installed were built for a different
+type of computer (an i686 with a GNU Linux kernel).
+
+There is an extremely slim chance that if your kernel has Linux Binary
+Compatibility (as do some variants of BSD), everything may work anyway, but
+you're probably best off reporting this to the gobolinux-users mailing list,
+and removing Rootless for the time being.
+"
+	rootless_uninstall
+fi
+
+###############################################################################
 # Packages Linking (Scripts, Rootless)
 ###############################################################################
 
 if [ -e "${goboPrefix}/Programs/Scripts/Current" ] 
 then
-	echo
-	echo Linking Scripts...
+	Log_Normal Linking Scripts...
+	UpdateSettings Scripts
 	SymlinkProgram Scripts
+elif [ ! -e "/Programs/Scripts/Current" ]; then
+	Log_Error "Installation failed"
+	rootless_uninstall
 fi
 
 echo
-echo Linking Rootless...
+Log_Normal Linking Rootless...
 SymlinkProgram Rootless
 
 
@@ -226,31 +329,30 @@ SymlinkProgram Rootless
 # Preparing Rootless startup on next sessions
 ###############################################################################
 
-for f in ${HOME}/.bashrc ${HOME}/.zshrc
+for f in .bash_profile .zshrc
 do
+	file="${HOME}/${f}"
 	line=". ${goboPrefix}/Programs/Rootless/Current/bin/StartRootless"
 	
-	#if [ -e ${f} ] && ! grep "^${line}" ${f} &> /dev/null
-	if ! grep "^${line}" ${f} &> /dev/null
+	if ! grep "^${line}" ${file} &> /dev/null
 	then
-		echo
-		echo "Appending \"$line\" to your ${f}" 
-		echo >> ${f}
-		echo "$line" >> ${f}
+		Log_Normal "Adding StartRootless line to ~/${f}"
+		echo >> ${file}
+		echo "$line" >> ${file}
 	fi
 done
-
 
 # Restores the last directory
 cd $pwd
 
-echo
-echo "Done!"
-echo
-echo "You can now restart your session in order to enjoy GoboLinux Rootless"
-echo
+Log_Terse "Installation complete."
+echo ""
+echo "You can now restart your session in order to enjoy GoboLinux Rootless. For"
+echo "best results, consider using the zsh shell."
+echo ""
 echo "Commands recommended to be executed afterwards:"
 echo "  InstallPackage Atool"
 echo "  InstallPackage Compile"
-echo "  InstallPackage Mtail"
-
+echo "  Compile Mtail"
+echo ""
+echo "Please report any problems to gobolinux-users@lists.gobolinux.org"
