Use all error code results of VerifyProgram

diff --git a/tools/Scripts/bin/InstallPackage b/tools/Scripts/bin/InstallPackage
--- a/tools/Scripts/bin/InstallPackage
+++ b/tools/Scripts/bin/InstallPackage
@@ -276,10 +276,35 @@ else
    tar "$taroption" "$archive" --backup=numbered -C ${goboPrograms} >&$verboseFD
 fi
 
-if Is_File "${goboPrograms}/${packagename}/${packageversion}/Resources/FileHash"
+verify_opts="--quiet"
+Boolean "verbose" && verify_opts="--verbose"
+VerifyProgram $verify_opts "$packagename" "$packageversion"
+result="$?"
+if [ $result -eq 0 ]
 then
-   VerifyProgram "$packagename" "$packageversion"
-#   Succeeded || Die "Unable to verify $1"
+   Log_Normal "Package Signature Verified"
+elif [ $result -eq 2 ]
+then
+   Log_Normal "GnuPG not installed.  Unable to verify signature"
+   Ask_Continue "Continue install?"
+elif [ $result -eq 4 ] 
+then
+   Log_Normal "No signature.  Unable to verify package"
+   Ask_Continue "Continue install?"
+elif [ $result -eq 5 ] 
+then
+   Log_Normal "No FileHash.  Unable to verify package"
+   Ask_Continue "Continue install?"
+elif [ $result -eq 1 ] 
+then
+   Log_Error "Invalid FileHash.  Package has been modified"
+   Log_Error "Suspect package in ${goboPrograms}/$packagename/$packageversion"
+   exit 1
+elif [ $result -eq 3 ] 
+then
+   Log_Error "Invalid Signature.  Package has been modified"
+   Log_Error "Suspect package in ${goboPrograms}/$packagename/$packageversion"
+   exit 1
 fi
 
 cd "${goboPrograms}/$packagename"
