Replaced usage of Dependencies to CheckDependencies. Btw, using --no-recursive and still calling dependencies checking after package installation. So, overall behaviour and assumptions are the same, but we gain features like new format Resources/Dependencies support.

diff --git a/tools/Scripts/bin/InstallPackage b/tools/Scripts/bin/InstallPackage
--- a/tools/Scripts/bin/InstallPackage
+++ b/tools/Scripts/bin/InstallPackage
@@ -310,7 +310,24 @@ SymlinkProgram "$packagename" "$packageversion"
 
 if ! Boolean "no-dependencies"
 then
-   Dependencies --check --keep-going --higher-or-missing-only ${batch} --execute "$0 $keep" "$packagename" "$packageversion"
+   if ! Boolean "no-dependencies" && ! Boolean "no-build"
+   then
+      Log_Normal "Checking dependencies..."
+      selecteddeps=`Temporary_File`
+      CheckDependencies --types=local_package,official_package --mode=missing \
+        --no-recursive --quiet-progress  "$packagename" "$packageversion" \
+        "installed" "${goboPrograms}/$packagename/$packageversion"  > $selecteddeps || Die "Aborted."
+      cat $selecteddeps | while read d_program d_version d_type d_url;
+      do
+         InstallPackage --no-dependencies $d_url || {
+            ret=$?
+            rm $selecteddeps
+            exit $ret
+         }
+      done
+      rm $selecteddeps
+   fi
+#   Dependencies --check --keep-going --higher-or-missing-only ${batch} --execute "$0 $keep" "$packagename" "$packageversion"
 fi
 
 Log_Verbose "Done."
