Fix for bu #2, cleaning up target directory when fibo sandbox fails

diff --git a/tools/Scripts/bin/SandboxInstall b/tools/Scripts/bin/SandboxInstall
--- a/tools/Scripts/bin/SandboxInstall
+++ b/tools/Scripts/bin/SandboxInstall
@@ -98,6 +98,19 @@ fi
 
 ### Install ####################################################################
 
+function installation_failed() {
+   # If not using UnionSandbox (including --no-sandbox" and rootless)
+   # undo symlink from Settings to Defaults/Settings
+   settings="$installPackageDir/Settings"
+   if ! [ "$unionsandbox" ]
+   then
+      Is_Link "${settings}" && rm "${settings}"
+      Is_Directory "${settings}.hold" && mv "${settings}.hold" "${settings}"
+      exit 1
+   fi
+   Die "Installation failed."
+}
+
 Log_Normal "Installing $package..."
 
 unset $expandsandbox
@@ -138,9 +151,9 @@ fi
 
 if Is_Entry "command"
 then
-   $sandbox `Entry "command"` "$@" || Die "Installation failed."
+   $sandbox `Entry "command"` "$@" || installation_failed
 else
-   $sandbox make -f "`Entry "makefile"`" "$@" `Entry "target"` || Die "Installation failed."
+   $sandbox make -f "`Entry "makefile"`" "$@" `Entry "target"` || installation_failed
 fi
 result="$?"
 
