code cleanups (incl. removing the UNIONSANDBOX flag) remove empty directories from leftovers

diff --git a/tools/Scripts/bin/SandboxInstall b/tools/Scripts/bin/SandboxInstall
--- a/tools/Scripts/bin/SandboxInstall
+++ b/tools/Scripts/bin/SandboxInstall
@@ -45,14 +45,17 @@ fi
 
 [ "$1" -o "$1" = "--" ] || Die "Argument missing: specify the program name."
 
-if [ `cat $goboStatus/filesystems | grep unionfs |wc -l` = "0" ] 
+unset unionsandbox
+
+if ! Boolean "no-sandbox" ]
 then
-    Log_Error "unionfs is unavailable.  Fallback to FiboSandbox!"
-    unset UNIONSANDBOX
-elif [ "$UNIONSANDBOX" != "false" ]
-then
-    Log_Normal "unionfs is available.  Using UnionSandbox!"
-    UNIONSANDBOX="true"
+   if [ `cat $goboStatus/filesystems | grep unionfs |wc -l` = "0" ] 
+   then
+      Log_Terse "unionfs is unavailable.  Fallback to FiboSandbox!"
+   else
+      Log_Normal "unionfs is available.  Using UnionSandbox!"
+      unionsandbox=yes
+   fi
 fi
 
 package="`basename "$1" /`"
@@ -111,21 +114,21 @@ Log_Verbose "Sandbox: $allowed"
 
 settings="$installPackageDir/Settings"
 default_settings="$installPackageDir/$version/Resources/Defaults/Settings"
-if [ "$UNIONSANDBOX" ] 
+if [ "$unionsandbox" ] 
 then
     sandbox_rw="$installPackageDir/$version/.SandboxInstall_Root"
     map_settings="--map ${default_settings}=${settings}"
-    fibosandbox="UnionSandbox -w $sandbox_rw -s $allowed $map_settings"
+    sandbox="UnionSandbox -w $sandbox_rw -s $allowed $map_settings"
 else
-    fibosandbox="FiboSandbox -s $allowed"
+    sandbox="FiboSandbox -s $allowed"
 fi
 
-Boolean "no-sandbox" && fibosandbox=
-[ "$ROOTLESS_GOBOLINUX" ] && fibosandbox=
+Boolean "no-sandbox" && sandbox=
+[ "$ROOTLESS_GOBOLINUX" ] && sandbox=
 
 # If not using UnionSandbox (including --no-sandbox" and rootless)
 # symlink Settings to Defaults/Settings
-if [ "$UNIONSANDBOX" = "" ] || [ "$fibosandbox" = "" ]
+if ! [ "$unionsandbox" ]
 then
     Assert_Dir $default_settings
     Is_Directory "${settings}" && mv "${settings}" "${settings}.hold"
@@ -134,22 +137,25 @@ fi
 
 if Is_Entry "command"
 then
-   $fibosandbox `Entry "command"` "$@" || Die "Installation failed."
+   $sandbox `Entry "command"` "$@" || Die "Installation failed."
 else
-   $fibosandbox make -f "`Entry "makefile"`" "$@" `Entry "target"` || Die "Installation failed."
+   $sandbox make -f "`Entry "makefile"`" "$@" `Entry "target"` || Die "Installation failed."
 fi
 result="$?"
 
-if [ "$UNIONSANDBOX" = "" ] || [ "$fibosandbox" = "" ]
+if ! [ "$sandbox" ]
 then
     Is_Link "${settings}" && rm "${settings}"
     Is_Directory "${settings}.hold" && mv "${settings}.hold" "${settings}"
 fi
 
-if [ "$UNIONSANDBOX" ] && [ "$fibosandbox" ]
+if [ "$unionsandbox" ]
 then
    # Postprocess contents of $sandbox_rw here
    Log_Normal "Postprocessing Sandbox"
+   Quiet pushd $sandbox_rw
+   find -type d | xargs rmdir -p --ignore-fail-on-non-empty
+   Quiet popd
    leftovers=`(cd $sandbox_rw; find *) 2>/dev/null`
    [ "$leftovers" ] && {
       Log_Normal "Left over files:\n$leftovers"
@@ -159,4 +165,5 @@ then
    }
    Quiet rmdir $sandbox_rw
 fi
+
 exit $result
