Define and use error return codes for VerifyProgram

diff --git a/tools/Scripts/bin/VerifyProgram b/tools/Scripts/bin/VerifyProgram
--- a/tools/Scripts/bin/VerifyProgram
+++ b/tools/Scripts/bin/VerifyProgram
@@ -6,6 +6,12 @@ Import GoboLinux
 Import File
 Import String
 
+######## Error codes ########
+# 0     No Error
+# 1     FileHash check failed
+# 2     No GnuPG or setup error
+# 3     Signature check failed
+
 ######## Changelog ########
 #
 # 09/12/2005 - [calica] Move gpg verify code to Functions/File
@@ -38,46 +44,6 @@ Parse_Options "$@"
 shift $parsedArguments
 
 ### Utility functions ################################################################
-function check_filehashes() {
-### python check_filehashes CHANGELOG
-# 10/10/2004 - [calica] First version
-   Parameters "$@" file
-   
-python -c """
-import re, os, string, os.path, sys
-
-hashfile='Resources/FileHash'
-
-file_checksums={}
-errors=0
-
-hashes = file(hashfile, 'r')
-for line in hashes:
-   fields = re.split('\s+', line)
-   file_checksums[fields[1]]=fields[0]
-   
-# Walk file tree
-for line in sys.stdin:
-   line = line.rstrip()
-   try:
-      good_md5 = file_checksums[line]
-      test_md5 = re.split('\s+', os.popen('md5sum %s'%line).read().rstrip())[0]
-      del file_checksums[line]
-      if good_md5 != test_md5:
-         print line, 'has been modified!'
-         errors+=1
-   except:
-      print line, 'not found in hashfile'
-      errors+=1
-
-for missing in file_checksums:
-   print missing, 'is missing'
-   errors+=1
-      
-sys.exit(errors)
-
-"""
-}
 
 ### Parse options #######################################################################
 package=`GuessProgramCase $1 $2`
@@ -123,11 +89,10 @@ then
    then
       Boolean "quiet" || Log_Normal "Verifying signature..."
       $quiet Check_FileSig "${FileHash_loc}" "${FileHash_sig}" 
-      rtn=$?
-      if [ $rtn -ne "0" ]
+      if Failed
       then
          Boolean "quiet" || Log_Error "Signature check failed: $rtn"
-         exit $rtn
+         exit 3
       fi
       Boolean "quiet" || Log_Normal "Signature OK"
    elif ! Boolean "no-signature"
@@ -136,21 +101,21 @@ then
    fi
 else
    Log_Error "GnuPG not installed."
+   result=2
 fi
+
 if Exists "${FileHash_loc}"
 then
    Boolean "quiet" || Log_Normal "Verifying FileHash..."
-#   $quiet md5sum --check "${FileHash_loc}"
-#   output=`find * -type f | grep -v "Resources/FileHash" | check_filehashes`
    output=`Check_FileHash "$prefix" "Resources/FileHash"`
-   rtn=$?
-   if [ $rtn -ne "0" ]
+   if Failed
    then
       Boolean "quiet" || Log_Error "FileHash check failed: $rtn"
       echo $output
-      exit $rtn
+      exit 3
    fi
    Boolean "quiet" || Log_Normal "FileHash OK"
 else
    Boolean "quiet" || Log_Error "No FileHash to verify."
 fi
+exit $result
