Failsafe when theme is invalid.

diff --git a/tools/BootScripts/bin/BootDriver b/tools/BootScripts/bin/BootDriver
--- a/tools/BootScripts/bin/BootDriver
+++ b/tools/BootScripts/bin/BootDriver
@@ -34,6 +34,13 @@ done
 
 ### Launch the actual scripts ###
 
+local theme="$BootScriptsDir/Themes/$BootTheme"
+if ! [ -e "$theme" ]
+then 
+   echo "Theme $BootTheme not found. Reverting to failsafe."
+   theme="$BootScriptsDir/Themes/Slack"
+fi
+
 source "$BootScriptsDir/Themes/$BootTheme"
 
 ThemeInit
