Checking if all required packages are present before installing any of them.

diff --git a/tools/BuildLiveCD/bin/BuildRoot b/tools/BuildLiveCD/bin/BuildRoot
--- a/tools/BuildLiveCD/bin/BuildRoot
+++ b/tools/BuildLiveCD/bin/BuildRoot
@@ -21,6 +21,19 @@ then
     exec sudo -u "#0" $0 $*
 fi
 
+cat $packagelists | while read line
+do
+   packagename=`echo $line |cut -d' ' -f1`
+   packagever=`echo $line |cut -d' ' -f2`
+   pkg=`ls $packagedir/${packagename}--${packagever}* 2> /dev/null || true`
+   [ ! "$pkg" ] && pkg=`ls $packagedir/${packagename}--* 2> /dev/null | tail -n 1` # Need better version compare code
+   [ ! "$pkg" ] && {
+      echo "*** Package $packagename could not be filled. ***"
+      exit 1
+   }
+done
+
+
 function do_link() {
    if [ -d "$root/$1" ]
    then
