A lot of enhancements implemented while being offline:
- Adapted BuildRoot and CompressAndBuildISO to update packages (and other items) on ROLayer, avoiding the need to remove the whole ROLayer directory
every time an external tarball is changed (md5sum is used). Warning: assuming there is only one version per program (can be improved in the future,
if needed).

- Removed the "External" directory, which contained unpacked tarballs. Now, CompressAndBuildISO is getting the files always directly from the
tarballs when inserting them in ROLayer and initrd. This avoids unnecessary local replication, removes a possible point of failure and allows a
better control of what has and what has not to be updated on an existing ROLayer. As a side effect, "mode" does not need to be set at
'Packages-Devel-i686', since only 'fetch' mode is used now.

- Cleanup on ChrootEnvironment: removed most of the 'convenience binds', since they can be harmful (e.g., rm -rf follows the binded dirs) and they
are not so useful anymore (most of the work is now done without having to be inside ChrootEnviroment). Only Chroot_Mount_CD-ROM bind was kept.

- Removed Master.conf: the directories listed at Master.conf were already hardcoded within the scripts. Don't having to deal with this configuration
file simplifies the overall idea of BuildLiveCD scripts. We can re-add Master.conf latter, with a better support on the scripts. Btw, a concept
similar to layering is already implemented with separated squashfs files and packages lists (stored at Data directory).

- Moved RWLayer to Output, since having it at the same level as ROLayer makes more sense (IMHO).

- Creating most directories "on-demand" (tm). E.g.: Output/RWLayer is now created only on ChrootEnvironment; Output/Enviromnent is created and
removed at each ChrootEnvironment call.

- Better isolation of each phase on both UpdateEnvironment and CompressAndBuildISO.

- UpdateEnvironment has now only download-related tasks. It gets Archives, CVS and Packages. (Unpacks and directory creations - other than
Archives/* and LocalCVS - are not needed anymore.)

- Removing old gobo-tools snapshots each time a new version is packed.

- Updated CD-Bootloader-i686.tar.bz2 file, pushing files one directory up (removed root i686 directory: isolinux and README are now at top level);
(Having README file inside bootloader tarball does not make much sense, but it is easy to change this latter.)

diff --git a/tools/BuildLiveCD/bin/BuildRoot b/tools/BuildLiveCD/bin/BuildRoot
--- a/tools/BuildLiveCD/bin/BuildRoot
+++ b/tools/BuildLiveCD/bin/BuildRoot
@@ -31,7 +31,6 @@ function get_package_name() {
    then packagever=`date +%Y%m%d`
    else packagever=`echo $1 | awk {'print $2'}`
    fi
-
    pkg=`ls $packagedir/${packagename}--${packagever}--* 2> /dev/null || true`
    [ -z "$pkg" ] && pkg=`ls $packagedir/${packagename}--* 2> /dev/null || true`
    if [ -z "$pkg" ]
@@ -47,7 +46,7 @@ function get_package_name() {
 cat $packagelists | while read line
 do
    # just ensure that required packages are found
-   get_package_name "$line"
+   get_package_name "$line" > /dev/null
 done
 
 
@@ -99,8 +98,17 @@ function symlink_program() {
    do_link ${full_path}/Shared ${gobolinks}/Shared
 
    [ -f "${root}${full_path}/Resources/Environment" ] && \
-   ln -nfs ${full_path}/Resources/Environment ${root}${gobolinks}/Environment/${name}--${version}
+   ln -nfs ../../../Programs/${name}/${version}/Resources/Environment ${root}${gobolinks}/Environment/${name}--${version}
    ln -nfs $version ${root}$(dirname ${full_path})/Current
+}
+
+function program_md5() {
+   #
+   # BIG FAT WARNING:
+   # Assuming we have only one version per program
+   #
+   name="$1"
+   cat "${root}"/../Checksums/$name--* 2> /dev/null | tail -1 || echo "0000"
 }
 
 function install_package() {
@@ -112,8 +120,31 @@ function install_package() {
    version=${base#*--}
    version=${version%%--*}
    
-   echo "Installing $name $version..."
+   #
+   # BIG FAT WARNING:
+   # Assuming we have only one version per program
+   #
+   packagemd5=`md5sum $package`
+   if [ -d "$root/Programs/$name" ]
+   then 
+      if [ "`program_md5 $name`" =  "$packagemd5" ]
+      then
+         echo "Keeping $name $version..."
+
+         # just keep package: md5 matches last installation
+         return
+      else
+         echo "Removing existing $name..."
+
+         # cleanup old md5 file
+         rm -f "${root}"/../Checksums/$name--*
+         # remove the installed package: $package was updated 
+         rm -rf "$root/Programs/$name"
+      fi
+   fi
+   echo "$packagemd5" > "${root}"/../Checksums/$name--$version
    
+   echo "Installing $name $version..."
    pushd "$root/Programs" &> /dev/null
    tar xjpf "$package"
 
@@ -137,10 +168,6 @@ function install_package() {
    symlink_program /Programs/$name/$version $root
 
 }
-
-echo "BuildRoot: Cleaning up $root if any..."
-
-rm -rf $root
 
 echo "BuildRoot: Building root $root..."
 
@@ -208,36 +235,34 @@ ln -nfs /System/Links/Manuals $root/usr/man
 ln -nfs /System/Links/Executables $root/usr/sbin
 ln -nfs /System/Links/Shared $root/usr/share
 
-mknod -m0666 $root/System/Kernel/Devices/null c 1 3
-mknod -m0600 $root/System/Kernel/Devices/console c 5 1
+[ -e $root/System/Kernel/Devices/null ] || mknod -m0666 $root/System/Kernel/Devices/null c 1 3
+[ -e $root/System/Kernel/Devices/null ] || mknod -m0600 $root/System/Kernel/Devices/console c 5 1
 
 pushd $root/System/Settings &> /dev/null
+# MakeSystemSettings overwrites existing files
 MakeSystemSettings
 popd &> /dev/null
 
-# cp -r Recipes $root/Files/Compile
-# 
-cat $packagelists |while read line
+mkdir -p "${root}"/../Checksums/
+
+for packagelist in ${packagelists[@]}
 do
-   pkg=`get_package_name $line`
-   install_package "$pkg" "$root"
+   echo "Installing packages from $packagelist"
+   cat $packagelist | while read line
+   do
+      pkg=`get_package_name $line`
+      install_package "$pkg" "$root"
+   done
 done
 
 [ -f "${root}/System/Links/Environment/Cache}" ] && rm ${root}/System/Links/Environment/Cache
 for link in ${root}/System/Links/Environment/*--*
 do
-   file=`readlink $link`
-   cat ${root}${file} >>${root}/System/Links/Environment/Cache
+   cat ${link} >>${root}/System/Links/Environment/Cache
 done
 
-function rm_if_e() {
-   if [ -e "$1" ]
-   then
-      echo "BuildRoot: removing $1..."
-      rm -f "$1"
-   else
-      return 0
-   fi
-}
+# SymlinkProgram --relative is not perfect yet, but, ideally, we should call the following command
+#echo "Checking for broken links at ${root}/System/Links/"
+#find ${root}/System/Links/ | RemoveBroken
 
 exit 0
diff --git a/tools/BuildLiveCD/bin/ChrootEnvironment b/tools/BuildLiveCD/bin/ChrootEnvironment
--- a/tools/BuildLiveCD/bin/ChrootEnvironment
+++ b/tools/BuildLiveCD/bin/ChrootEnvironment
@@ -1,17 +1,11 @@
 #!/bin/sh
 
-for conf in ./Master.conf /System/Settings/BuildLiveCD/Master.conf fail
-do
-   if [ "$conf" = "fail" ]
-   then
-      echo "Could not find Master.conf."
-      exit 1
-   elif [ -e $conf ]
-   then
-      source $conf
-      break
-   fi
-done
+if [ ! -d "Output/ROLayer" ]
+then
+   echo "Error: Output/ROLayer doesn't exist."
+   echo "Please run CompressAndBuildISO prior before trying to ChrootEnvironment"
+   exit 1
+fi
 
 if [ "$UID" != "0" ]
 then
@@ -19,54 +13,48 @@ then
     exec sudo -u "#0" $0 $*
 fi
 
+echo "Unionfs mounting layers."
+
+chroot_layers=(
+   "Output/RWLayer=rw"
+   "Output/ROLayer=ro"
+)
+unionfs_dirs=`echo "${chroot_layers[@]}" | tr " " ":"`
 mp="Output/Environment"
-if [ -d "$mp" ]
-then
-   echo "Unionfs mounting layers."
-   unionfs_dirs=`echo "${chroot_layers[@]}" | tr " " ":"`
-   mkdir -p RWLayer
-   echo mount -t unionfs -o "dirs=${unionfs_dirs}" none ${mp}
-   mount -t unionfs -o "dirs=${unionfs_dirs}" none ${mp} || { echo Error mounting Output/Environment; exit 1; }
-   
-   mkdir -p Output/Chroot_Mount_CD-ROM/{Programs_Local,Depot_Local,Users_Local,Packages}
+mkdir -p Output/RWLayer
+mkdir -p $mp
 
-   # Convenience access to directories from the host environment
-   echo "Binding ${mp}/Mount/CD-ROM ..."
-   mount -o bind Output/Chroot_Mount_CD-ROM ${mp}/Mount/CD-ROM
-   mount -o bind /Programs                  ${mp}/Mount/CD-ROM/Programs_Local
-   mount -o bind /Depot                     ${mp}/Mount/CD-ROM/Depot_Local
-   mount -o bind /Users                     ${mp}/Mount/CD-ROM/Users_Local
-   mount -o bind Archives/Packages          ${mp}/Mount/CD-ROM/Packages
+echo mount -t unionfs -o "dirs=${unionfs_dirs}" none ${mp}
+mount -t unionfs -o "dirs=${unionfs_dirs}" none ${mp} || { echo Error mounting Output/Environment; exit 1; }
 
-   echo "        ${mp}/System/Kernel/Devices ..."
-   mount -o bind /System/Kernel/Devices ${mp}/System/Kernel/Devices
-   echo "        ${mp}/System/Kernel/Status ..."
-   mount -o bind /System/Kernel/Status ${mp}/System/Kernel/Status
+# Convenience access to directories from the host environment
+mkdir -p Output/Chroot_Mount_CD-ROM
+echo "Binding ${mp}/Mount/CD-ROM ..."
+mount -o bind Output/Chroot_Mount_CD-ROM ${mp}/Mount/CD-ROM
+echo "        ${mp}/System/Kernel/Devices ..."
+mount -o bind /System/Kernel/Devices ${mp}/System/Kernel/Devices
+echo "        ${mp}/System/Kernel/Status ..."
+mount -o bind /System/Kernel/Status ${mp}/System/Kernel/Status
 
-   echo "Chrooting into ${mp} "
-   chroot ${mp}
+echo "Chrooting into ${mp} "
+chroot ${mp}
+sync
 
-   sync
+#####################################################################
 
-   #####################################################################
+echo "Cleaning up /tmp..."
+rm -fr -- ${mp}/tmp/*
 
-   echo "Cleaning up /tmp..."
-   rm -fr -- ${mp}/tmp/*
+echo "Unmounting:"
+mp_path=`readlink -f ${mp}`
+cat /proc/mounts | tac | cut -d' ' -f2 | grep $mp_path | while read dir
+do
+   echo "  ${dir}"
+   umount "${dir}"
+done
 
-   echo "Unmounting:"
-   mp_path=`readlink -f ${mp}`
-   cat /proc/mounts | tac | cut -d' ' -f2 |grep $mp_path | \
-   while read dir
-   do
-      echo "  ${dir}"
-      umount "${dir}"
-   done
-
-   rmdir --ignore-fail-on-non-empty -p Output/Chroot_Mount_CD-ROM/{Programs_Local,Depot_Local,Users_Local,Packages}
-
-else
-   echo "Error: $mp doesn't exist."
-fi
+rmdir ${mp}
+rmdir --ignore-fail-on-non-empty -p Output/Chroot_Mount_CD-ROM
 
 # additional things to check before releasing a LiveCD
 # cd /Programs/; time for i in *; do echo $i; mkdir $i/Current/Resources/; Dependencies $i > $i/Current/Resources/Dependencies; done
diff --git a/tools/BuildLiveCD/bin/CompressAndBuildISO b/tools/BuildLiveCD/bin/CompressAndBuildISO
--- a/tools/BuildLiveCD/bin/CompressAndBuildISO
+++ b/tools/BuildLiveCD/bin/CompressAndBuildISO
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-kernel_version=`sed -n 's,.*--\(.*\)--kernel.*,\1,p' /Programs/BuildLiveCD/Current/Data/Packages-Devel-i686`
-
 if [ "$1" = "--help" ]
 then
    echo "$0 [<start_stage> [<end_stage>]]"
@@ -24,7 +22,8 @@ then
    "iso")      start_at=$STAGE_ISO;;
    esac
 else
-   [ -d "Output/ROLayer" ] && start_at=$STAGE_SQUASHFS || start_at=$STAGE_ROLAYER
+   start_at=$STAGE_ROLAYER
+   #[ -d "Output/ROLayer" ] && start_at=$STAGE_SQUASHFS || 
 fi
  
 if [ "$2" ]
@@ -39,105 +38,143 @@ else
    stop_at=$STAGE_ISO
 fi
 
-if ! which mksquashfs &> /dev/null
-then
-   echo "You need to install SquashFS-Tools."
-   exit 1
-fi
-
-for conf in ./Master.conf /System/Settings/BuildLiveCD/Master.conf fail
-do
-   if [ "$conf" = "fail" ]
-   then
-      echo "Could not find Master.conf."
-      exit 1
-   elif [ -e $conf ]
-   then
-      source $conf
-      break
-   fi
-done
-
 if [ "$UID" != "0" ]
 then
     echo "Running as superuser."
     exec sudo -u "#0" $0 $*
 fi
 
-datadir="/Programs/BuildLiveCD/Current/Data" 
-tools=`cat $datadir/Packages-List-GoboLinuxTools`
-today=`date +%Y%m%d`
-arch=`uname -m`
 
 root=$PWD
-localcvs=$PWD/LocalCVS/
-packages=$PWD/Archives/Packages
-externalarchives=$PWD/Archives/Ext
-external=$PWD/External
+kernel_version=`sed -n 's,.*--\(.*\)--kernel.*,\1,p' /Programs/BuildLiveCD/Current/Data/Packages-Devel-i686`
+arch=i686
+today=`date +%Y%m%d`
+localcvs=$root/LocalCVS
+packages=$root/Archives/Packages
 
-if ! [ -e $localcvs -a -e $packages -a -e $external ] 
-then
-   echo 'Basic directories could not be found.'
-   echo 'Please check if you are running the script inside a directory populated by UpdateEnviromnent'
-   exit 1
-fi 
-
+#############################################################################
+# ROLayer
+#############################################################################
 if [ "$start_at" -le "$STAGE_ROLAYER" ] && [ "$stop_at" -ge "$STAGE_ROLAYER" ]
 then
    echo "=> ROLayer stage started"
-   
-   cd $packages
+
+   if ! [ -e LocalCVS -a -e Archives/Packages -a -e Archives/Ext ]
+   then
+      echo 'Basic directories could not be found.'
+      echo 'Please check if you are running the script inside a directory populated by UpdateEnviromnent'
+      exit 1
+   fi
+
+   datadir="/Programs/BuildLiveCD/Current/Data" 
+   tools=`cat $datadir/Packages-List-GoboLinuxTools`
+
+   toolswhichneedmake=""
+   cd "$packages"
    for package in $tools 
    do
-      echo "Packing $package CVS snapshot..."
       tarball=$package--$today--$arch.tar.bz2
-      rm -rf $package
-      mkdir -p $package/$today
-      cp -a $localcvs/tools/$package/* $package/$today
-      cd $package/$today
-      # we need to build here in order to create the files which are going to be linked inside BuildRoot
-      [ -e Makefile ] && make > /dev/null 
-      find -type d -name CVS | xargs rm -rf 
-      cd ..
-      ln -nfs $today Current
-      cd ..
-      rm -f $tarball
-      tar cjpf $tarball $package
-      rm -rf $package
+
+      if [ ! -e "$tarball" -o "`find "$localcvs/tools/$package/" -newer "$tarball" 2> /dev/null`" ] 
+      then
+         echo "Packing $package CVS snapshot..."
+         rm -rf $package                    # only required if there are leftovers from a previous execution
+         mkdir -p $package
+         cp -a $localcvs/tools/$package $package/$today
+         # we need to build here in order to create the files which are going to be linked inside BuildRoot
+         [ -e $package/$today/Makefile ] && echo Building $package/$today && make -C $package/$today > /dev/null 
+         find $package/$today/ -type d -name CVS | xargs rm -rf 
+         rm -f $package--*--$arch.tar.bz2   # cleaning up old versions too
+         tar cjpf $tarball $package/$today  # create the package
+         rm -rf $package
+         toolswhichneedmake="$toolswhichneedmake $package"
+      else
+         echo "Don't repacking $package CVS snapshot..."
+      fi
+
    done
-   cd $root
 
+   echo
    echo "Building root..."
+   cd "$root"
    BuildRoot "Output/ROLayer" "Archives/Packages" $datadir/Packages-List-* || exit 1
-
-   echo "Rebuilding tools..." 
+   
+   echo
+   cd "$root"
    for package in $tools 
    do
       # we build the tools again to ensure they are prepared to the LiveCD environment
-      [ -e $root/$package/$today/Makefile ] && { chroot $root make clean; chroot $root make all; } > /dev/null
+      if [ -e Output/ROLayer/Programs/$package/$today/Makefile ] && echo "$toolswhichneedmake" | grep "$package" &> /dev/null 
+      then 
+         echo "Rebuilding $package..." 
+         chroot Output/ROLayer make -C Programs/$package/$today/ clean  
+         chroot Output/ROLayer make -C Programs/$package/$today/        
+      fi
    done
 
+   echo "Coping /Files from LocalCVS..."
    # Add few items to rolayer
+   rm -rf Output/ROLayer/Files/{Documents,Descriptions,Wallpapers}
    mkdir -p Output/ROLayer/Files
-   cp -ar LocalCVS/files/* Output/ROLayer/Files
-   cp -ar External/Files-Fonts/* Output/ROLayer/Files
-   #mkdir -p Output/ROLayer/Files/Documentation
-   cp -ar External/Linux-Kernel/* Output/ROLayer
+   cp -a LocalCVS/files/* Output/ROLayer/Files
+
+   # /Files/Fonts
+   ffontsmd5=`md5sum Archives/Ext/Files-Fonts.tar.bz2`
+   if [ -d "Output/ROLayer/Files/Fonts" ]
+   then
+      ffontsmd5old=`cat Output/Checksums/Files-Fonts`
+   fi
+   if [ "$ffontsmd5" = "$ffontsmd5old" ]
+   then
+      echo "Keeping /Files/Fonts..."
+   else
+      echo "Unpacking /Files/Fonts..."
+      tar xfj Archives/Ext/Files-Fonts.tar.bz2 --overwrite -C Output/ROLayer/Files
+      echo "$ffontsmd5" > Output/Checksums/Files-Fonts
+   fi
+
+   # /System/Kernel/{Modules,Boot}
+   kernelmd5=`md5sum Archives/Ext/Linux--$kernel_version--kernel-i686.tar.bz2`
+   if [ -d "Output/ROLayer/System/Kernel/Modules" -a -d "Output/ROLayer/System/Kernel/Boot" ]
+   then
+      kernelmd5old=`cat Output/Checksums/Kernel 2> /dev/null`
+   fi
+   if [ "$kernelmd5" = "$kernelmd5old" ]
+   then
+      echo "Keeping kernel files..."
+   else
+      echo "Unpacking kernel files..."
+      rm -rf Output/ROLayer/System/Kernel/{Modules,Boot}
+      tar xfj Archives/Ext/Linux--$kernel_version--kernel-i686.tar.bz2 --overwrite -C Output/ROLayer
+      echo "$kernelmd5" > Output/Checksums/Kernel
+   fi
 
    # Clean CVS files from ROLayer
    echo "Removing CVS files..."
    find Output/ROLayer/Files -type d -name CVS | xargs rm -rf
+
    echo "=> ROLayer stage done"
 fi
 
-mkdir -p Output/ISO
-
+#############################################################################
+# Squashfs
+#############################################################################
 if [ "$start_at" -le "$STAGE_SQUASHFS" ] && [ "$stop_at" -ge "$STAGE_SQUASHFS" ]
 then
    echo "=> SquashFS stage started"
+   if ! which mksquashfs &> /dev/null
+   then
+      echo "You need to install SquashFS-Tools."
+      exit 1
+   fi
 
+   build_layers=(
+      "Output/RWLayer=ro"
+      "Output/ROLayer=ro"
+   )
    unionfs_dirs=`echo "${build_layers[@]}" | tr " " ":"`
    mkdir -p Output/Environment
+   mkdir -p Output/RWLayer
    echo "Unionfs mounting layers."
    tmp_mp=`mktemp -d /tmp/finalize_layer-XXXXX`
    unionfs_dirs="dirs=${tmp_mp}=rw:${unionfs_dirs}"
@@ -196,6 +233,7 @@ then
    md5sum Output/Environment/Programs/Glibc/Settings/ld.so.cache > Output/ld.so.cache.sum
 
    # compress the uncompressed files into squashfs files
+   mkdir -p Output/ISO
    time mksquashfs_on_demand Output/ISO/GoboLinux-files.squashfs Output/Environment/Files
    for i in $datadir/Packages-List-*; do 
       time mksquashfs_on_demand Output/ISO/`basename $i`.squashfs `cat $i | cut -f 1 -d ' ' | sort -u | while read i; do echo Output/Environment/Programs/$i; done`
@@ -203,15 +241,29 @@ then
    time mksquashfs_on_demand Output/ISO/GoboLinux-rest.squashfs `ls -d Output/Environment/* | grep -v Files | grep -v Programs | grep -v Users`
 
    umount Output/Environment
+   rmdir Output/Environment
    rm -rf $tmp_mp
    echo "=> SquashFS stage done"
 fi
 
-cp -ra External/CD-Bootloader/$arch/. Output/ISO/
-
+#############################################################################
+# InitRD
+#############################################################################
 if [ "$start_at" -le "$STAGE_INITRD" ] && [ "$stop_at" -ge "$STAGE_INITRD" ]
 then
    echo "=> InitRD stage started"
+
+   if ! [ -e Archives/InitRD ]
+   then
+      echo 'Basic directory Archives/InitRD could not be found.'
+      echo 'Please check if you are running the script inside a directory populated by UpdateEnviromnent'
+      exit 1
+   fi
+
+   mkdir -p Output/ISO
+   echo "Unpacking CD-Bootloader..."
+   tar  xfj Archives/Ext/CD-Bootloader-$arch.tar.bz2 --overwrite -C Output/ISO/
+
    #Rebuild initrd
    initrd_dir=Output/InitRD
 
@@ -221,6 +273,7 @@ then
       echo "Packing $package CVS snapshot..."
       tarball=$package--$today--$arch.tar.bz2
       rm -rf $package
+      rm $package--*
       mkdir -p $package/$today
       cp -a $localcvs/tools/$package/* $package/$today
       cd $package/$today
@@ -229,23 +282,25 @@ then
       cd ..
       ln -nfs $today Current
       cd ..
-   
       rm -f $tarball
       tar cjpf $tarball $package
       rm -rf $package
    done
    cd $root
-   
+
    MakeInitRDTree
-   cp External/Linux-Kernel/System/Kernel/Boot/kernel-$kernel_version Output/ISO/isolinux/kernel
+   echo "Extracting isolinux/kernel from Archives/Ext/Linux--${kernel_version}--kernel-i686.tar.bz2"
+   tar xfj Archives/Ext/Linux--${kernel_version}--kernel-i686.tar.bz2  System/Kernel/Boot/kernel-${kernel_version} -O > Output/ISO/isolinux/kernel
    mkfs.cramfs $initrd_dir Output/ISO/isolinux/initrd
    echo "=> InitRD stage done"
 fi
 
+#############################################################################
+# ISO
+#############################################################################
 if [ "$start_at" -le "$STAGE_ISO" ] && [ "$stop_at" -ge "$STAGE_ISO" ]
 then
    echo "=> ISO stage started"
-   # having the squashfs file, you can prepare the bootable iso
    iso_name="Output/GoboLinux-NoVersion.iso"
    time nice -20 mkisofs -R -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table Output/ISO  > $iso_name
    echo "=> ISO stage done"
