General improvements.

diff --git a/tools/BuildLiveCD/bin/ChrootEnvironment b/tools/BuildLiveCD/bin/ChrootEnvironment
--- a/tools/BuildLiveCD/bin/ChrootEnvironment
+++ b/tools/BuildLiveCD/bin/ChrootEnvironment
@@ -1,6 +1,17 @@
 #!/bin/sh
 
-. Master.conf
+for conf in ./Master.conf /System/Settings/BuildLiveCD/Master.conf fail
+do
+   if [ "$conf" = "fail" ]
+   then
+      echo "Could not find Master.conf."
+      exit 1
+   elif [ -e $conf ]
+   then
+      source $conf
+      break
+   fi
+done
 
 mp="output/Environment"
 layer1="output/Layer1"
diff --git a/tools/BuildLiveCD/bin/CompressAndBuildISO b/tools/BuildLiveCD/bin/CompressAndBuildISO
--- a/tools/BuildLiveCD/bin/CompressAndBuildISO
+++ b/tools/BuildLiveCD/bin/CompressAndBuildISO
@@ -6,7 +6,18 @@ then
    exit 1
 fi
 
-. Master.conf
+for conf in ./Master.conf /System/Settings/BuildLiveCD/Master.conf fail
+do
+   if [ "$conf" = "fail" ]
+   then
+      echo "Could not find Master.conf."
+      exit 1
+   elif [ -e $conf ]
+   then
+      source $conf
+      break
+   fi
+done
 
 if [ "$UID" != "0" ]
 then
@@ -21,7 +32,7 @@ mkdir -p output/ISO
 if [ "$start_at" = "layer1" ] || ! [ -d "output/Layer1" ]
 then
     mkdir -p output/Layer1
-    LiveCD_work/Scripts/BuildRoot "output/Layer1" "Packages" "Packages/package.list"
+    BuildRoot "output/Layer1" "Packages" "Packages/package.list"
     [ "$?" = "0" ] || exit 1
 
     # Add few items to layer1
@@ -65,29 +76,38 @@ then
     mount -t unionfs -o ${unionfs_dirs} none output/Environment
 
     mkdir -p output/Checksums
+    
+    function ld_so_cache_changed() {
+       if grep -q "output/Environment/Programs/Glibc/Settings/ld.so.cache" /tmp/newer.txt
+       then
+          diff output/ld.so.cache.sum output/ld.so.cache.sum.old &> /dev/null
+          if [ $? -ne 0 ]
+          then
+             cp output/ld.so.cache.sum output/ld.so.cache.sum.old
+             return 0
+          fi
+       else
+          return 1
+       fi
+    }
+    
     function mksquashfs_on_demand() {
        out="$1"
        shift
        bn=`basename "$out"`
        # sumsfile=output/Checksums/$bn.sums
        echo "Checking if $bn needs updating..."
+       find "$@" -type f -newer "$out" 2> /dev/null > /tmp/newer.txt
        echo ==========
        echo Changes:
        echo ----------
-       find "$@" -newer "$out" 2> /dev/null
+       cat /tmp/newer.txt
        echo ==========
-       find "$@" -newer "$out" 2> /dev/null > /tmp/newer.txt
-       diffs=`cat /tmp/newer.txt | wc -l`
-       if [ ! -e "$out" ] || [ $diffs -gt 0 ]
+       diffs=`cat /tmp/newer.txt | grep -v "output/Environment/Programs/Glibc/Settings/ld.so.cache" | wc -l`
+       if [ ! -e "$out" ] || [ $diffs -gt 0 ] || ld_so_cache_changed
        #find "$@" | grep -v Devices | xargs -n 100 md5sum > $sumsfile.new 2> /dev/null
        #if ! diff -q $sumsfile $sumsfile.new
        then
-          if [ $diffs -eq 3 ] && grep -q "output/Environment/Programs/Glibc/Settings/ld.so.cache" /tmp/newer.txt
-          then
-             md5sum output/Environment/Programs/Glibc/Settings/ld.so.cache > output/ld.so.cache.sum.new
-             return
-          fi
-       
           echo "Creating squashfs compressed file $bn..."
           # mv $sumsfile.new $sumsfile
           nice -20 mksquashfs "$@" "$out" -noappend
@@ -115,7 +135,7 @@ then
     start_at="initrd"
 fi
 
-cp -ra LiveCD_work/ISO_Base/$arch/. output/ISO
+cp -ra Ext_work/ISO_Base/$arch/. output/ISO
 
 if [ "$start_at" = "initrd" ] || ! [ -f "output/ISO/isolinux/initrd.gz" ]
 then
