- Using gobo.calica.com for archives; - Merged initrd-devel and livecd-devel directories at the server, and downloading all archives to ./Archives directory. - Linux kernel is now a package, does not need special handling anymore.

diff --git a/tools/BuildLiveCD/bin/CompressAndBuildISO b/tools/BuildLiveCD/bin/CompressAndBuildISO
--- a/tools/BuildLiveCD/bin/CompressAndBuildISO
+++ b/tools/BuildLiveCD/bin/CompressAndBuildISO
@@ -57,7 +57,7 @@ kernel_version=`sed -n 's,.*--\(.*\)--kernel.*,\1,p' /Programs/BuildLiveCD/Curre
 arch=i686
 today=`date +%Y%m%d`
 localcvs=$root/LocalCVS
-packages=$root/Archives/Packages
+packages=$root/Packages
 datadir="/Programs/BuildLiveCD/Current/Data" 
    
 #############################################################################
@@ -67,7 +67,7 @@ if [ "$start_at" -le "$STAGE_ROLAYER" ] && [ "$stop_at" -ge "$STAGE_ROLAYER" ]
 then
    echo "=> ROLayer stage started"
 
-   if ! [ -e LocalCVS -a -e Archives/Packages -a -e Archives/Ext ]
+   if ! [ -e LocalCVS -a -e Packages -a -e Archives ]
    then
       echo 'Basic directories could not be found.'
       echo 'Please check if you are running the script inside a directory populated by UpdateEnviromnent'
@@ -107,7 +107,7 @@ then
    echo
    echo "Building root..."
    cd "$root"
-   BuildRoot "Output/ROLayer" "Archives/Packages" $datadir/Packages-List-* || exit 1
+   BuildRoot "Output/ROLayer" "Packages" $datadir/Packages-List-* || exit 1
    
    echo
    cd "$root"
@@ -137,7 +137,7 @@ then
    done
 
    # /Files/Fonts
-   ffontsmd5=`md5sum Archives/Ext/Files-Fonts.tar.bz2`
+   ffontsmd5=`md5sum Archives/Files-Fonts.tar.bz2`
    if [ -d "Output/ROLayer/Files/Fonts" ]
    then
       ffontsmd5old=`cat Output/Checksums/Files-Fonts`
@@ -147,27 +147,8 @@ then
       echo "Keeping /Files/Fonts..."
    else
       echo "Unpacking /Files/Fonts..."
-      tar xfj Archives/Ext/Files-Fonts.tar.bz2 --overwrite -C Output/ROLayer/Files
+      tar xfj Archives/Files-Fonts.tar.bz2 --overwrite -C Output/ROLayer/Files
       echo "$ffontsmd5" > Output/Checksums/Files-Fonts
-   fi
-
-   # /System/Kernel/{Modules,Boot}
-   kernelmd5=`md5sum Archives/Ext/Linux--$kernel_version--kernel-i686.tar.bz2`
-   if [ -d "Output/ROLayer/System/Kernel/Modules" -a -d "Output/ROLayer/System/Kernel/Boot" ]
-   then
-      kernelmd5old=`cat Output/Checksums/Kernel 2> /dev/null`
-   fi
-   if [ "$kernelmd5" = "$kernelmd5old" ]
-   then
-      echo "Keeping kernel files..."
-   else
-      echo "Unpacking kernel files..."
-      # We need to keep /S/K/Boot/grub here
-      rm -rf Output/ROLayer/System/Kernel/Modules
-      rm -f  Output/ROLayer/System/Kernel/Boot/kernel--*
-      rm -f  Output/ROLayer/System/Kernel/Boot/System.map--*
-      tar xfj Archives/Ext/Linux--$kernel_version--kernel-i686.tar.bz2 --overwrite -C Output/ROLayer
-      echo "$kernelmd5" > Output/Checksums/Kernel
    fi
 
    # Clean CVS files from ROLayer
@@ -274,21 +255,21 @@ if [ "$start_at" -le "$STAGE_INITRD" ] && [ "$stop_at" -ge "$STAGE_INITRD" ]
 then
    echo "=> InitRD stage started"
 
-   if ! [ -e Archives/InitRD ]
+   if ! [ -e Archives ]
    then
-      echo 'Basic directory Archives/InitRD could not be found.'
+      echo 'Basic directory Archives could not be found.'
       echo 'Please check if you are running the script inside a directory populated by UpdateEnviromnent'
       exit 1
    fi
 
    mkdir -p Output/ISO
    echo "Unpacking CD-Bootloader..."
-   tar  xfj Archives/Ext/CD-Bootloader-$arch.tar.bz2 --overwrite -C Output/ISO/
+   tar  xfj Archives/CD-Bootloader-$arch.tar.bz2 --overwrite -C Output/ISO/
 
    #Rebuild initrd
    initrd_dir=Output/InitRD
 
-   cd Archives/InitRD/
+   cd Archives/
    for package in InitRDScripts
    do
       echo "Packing $package CVS snapshot..."
@@ -310,8 +291,8 @@ then
    cd $root
 
    MakeInitRDTree || die "Failed creating initrd environment."
-   echo "Extracting isolinux/kernel from Archives/Ext/Linux--${kernel_version}--kernel-i686.tar.bz2"
-   tar xfj Archives/Ext/Linux--${kernel_version}--kernel-i686.tar.bz2 -O System/Kernel/Boot/kernel-${kernel_version}  > Output/ISO/isolinux/kernel
+   echo "Copying isolinux/kernel from Output/ROLayer/System/Kernel/Boot/kernel"
+   \cp --remove-destination Output/ROLayer/System/Kernel/Boot/kernel Output/ISO/isolinux/kernel
    mkfs.cramfs $initrd_dir Output/ISO/isolinux/initrd
    echo "=> InitRD stage done"
 fi
